window.esdocSearchIndex = [
  [
    "@fnndsc/chrisapi~allpipelineinstancelist",
    "class/src/pipelineinstance.js~AllPipelineInstanceList.html",
    "<span>AllPipelineInstanceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~allplugininstancelist",
    "class/src/plugininstance.js~AllPluginInstanceList.html",
    "<span>AllPluginInstanceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~allworkflowlist",
    "class/src/workflow.js~AllWorkflowList.html",
    "<span>AllWorkflowList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~chrisinstance",
    "class/src/chrisinstance.js~ChrisInstance.html",
    "<span>ChrisInstance</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~client",
    "class/src/client.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~collection",
    "class/src/cj.js~Collection.html",
    "<span>Collection</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~comment",
    "class/src/comment.js~Comment.html",
    "<span>Comment</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~commentlist",
    "class/src/comment.js~CommentList.html",
    "<span>CommentList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~computeresource",
    "class/src/computeresource.js~ComputeResource.html",
    "<span>ComputeResource</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~computeresourceadmin",
    "class/src/admin.js~ComputeResourceAdmin.html",
    "<span>ComputeResourceAdmin</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~computeresourceadminlist",
    "class/src/admin.js~ComputeResourceAdminList.html",
    "<span>ComputeResourceAdminList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~computeresourcelist",
    "class/src/computeresource.js~ComputeResourceList.html",
    "<span>ComputeResourceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feed",
    "class/src/feed.js~Feed.html",
    "<span>Feed</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedlist",
    "class/src/feed.js~FeedList.html",
    "<span>FeedList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedplugininstancelist",
    "class/src/plugininstance.js~FeedPluginInstanceList.html",
    "<span>FeedPluginInstanceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedtaglist",
    "class/src/tag.js~FeedTagList.html",
    "<span>FeedTagList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedtagginglist",
    "class/src/tag.js~FeedTaggingList.html",
    "<span>FeedTaggingList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~filebrowserfolder",
    "class/src/filebrowser.js~FileBrowserFolder.html",
    "<span>FileBrowserFolder</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~filebrowserfolderchildlist",
    "class/src/filebrowser.js~FileBrowserFolderChildList.html",
    "<span>FileBrowserFolderChildList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~filebrowserfolderfile",
    "class/src/filebrowser.js~FileBrowserFolderFile.html",
    "<span>FileBrowserFolderFile</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~filebrowserfolderfilelist",
    "class/src/filebrowser.js~FileBrowserFolderFileList.html",
    "<span>FileBrowserFolderFileList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~filebrowserfolderlinkfile",
    "class/src/filebrowser.js~FileBrowserFolderLinkFile.html",
    "<span>FileBrowserFolderLinkFile</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~filebrowserfolderlinkfilelist",
    "class/src/filebrowser.js~FileBrowserFolderLinkFileList.html",
    "<span>FileBrowserFolderLinkFileList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~filebrowserfolderlist",
    "class/src/filebrowser.js~FileBrowserFolderList.html",
    "<span>FileBrowserFolderList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~itemresource",
    "class/src/resource.js~ItemResource.html",
    "<span>ItemResource</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~listresource",
    "class/src/resource.js~ListResource.html",
    "<span>ListResource</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~note",
    "class/src/note.js~Note.html",
    "<span>Note</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pacsfile",
    "class/src/pacsfile.js~PACSFile.html",
    "<span>PACSFile</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pacsfilelist",
    "class/src/pacsfile.js~PACSFileList.html",
    "<span>PACSFileList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipeline",
    "class/src/pipeline.js~Pipeline.html",
    "<span>Pipeline</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipelineinstance",
    "class/src/pipelineinstance.js~PipelineInstance.html",
    "<span>PipelineInstance</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipelineinstancelist",
    "class/src/pipelineinstance.js~PipelineInstanceList.html",
    "<span>PipelineInstanceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipelineinstanceplugininstancelist",
    "class/src/plugininstance.js~PipelineInstancePluginInstanceList.html",
    "<span>PipelineInstancePluginInstanceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipelinelist",
    "class/src/pipeline.js~PipelineList.html",
    "<span>PipelineList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipelinepipingdefaultparameterlist",
    "class/src/pipeline.js~PipelinePipingDefaultParameterList.html",
    "<span>PipelinePipingDefaultParameterList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipelinepluginlist",
    "class/src/pipeline.js~PipelinePluginList.html",
    "<span>PipelinePluginList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipelinepluginpipinglist",
    "class/src/pipeline.js~PipelinePluginPipingList.html",
    "<span>PipelinePluginPipingList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipelinesourcefile",
    "class/src/pipeline.js~PipelineSourceFile.html",
    "<span>PipelineSourceFile</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipelinesourcefilelist",
    "class/src/pipeline.js~PipelineSourceFileList.html",
    "<span>PipelineSourceFileList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pipingdefaultparameter",
    "class/src/pipeline.js~PipingDefaultParameter.html",
    "<span>PipingDefaultParameter</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugin",
    "class/src/plugin.js~Plugin.html",
    "<span>Plugin</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginadmin",
    "class/src/admin.js~PluginAdmin.html",
    "<span>PluginAdmin</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginadminlist",
    "class/src/admin.js~PluginAdminList.html",
    "<span>PluginAdminList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugincomputeresourcelist",
    "class/src/computeresource.js~PluginComputeResourceList.html",
    "<span>PluginComputeResourceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstance",
    "class/src/plugininstance.js~PluginInstance.html",
    "<span>PluginInstance</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstancedescendantlist",
    "class/src/plugininstance.js~PluginInstanceDescendantList.html",
    "<span>PluginInstanceDescendantList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstancelist",
    "class/src/plugininstance.js~PluginInstanceList.html",
    "<span>PluginInstanceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstanceparameter",
    "class/src/plugininstance.js~PluginInstanceParameter.html",
    "<span>PluginInstanceParameter</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstanceparameterlist",
    "class/src/plugininstance.js~PluginInstanceParameterList.html",
    "<span>PluginInstanceParameterList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstancesplit",
    "class/src/plugininstance.js~PluginInstanceSplit.html",
    "<span>PluginInstanceSplit</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstancesplitlist",
    "class/src/plugininstance.js~PluginInstanceSplitList.html",
    "<span>PluginInstanceSplitList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginlist",
    "class/src/plugin.js~PluginList.html",
    "<span>PluginList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginmeta",
    "class/src/pluginmeta.js~PluginMeta.html",
    "<span>PluginMeta</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginmetalist",
    "class/src/pluginmeta.js~PluginMetaList.html",
    "<span>PluginMetaList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginmetapluginlist",
    "class/src/plugin.js~PluginMetaPluginList.html",
    "<span>PluginMetaPluginList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginparameter",
    "class/src/pluginparameter.js~PluginParameter.html",
    "<span>PluginParameter</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginparameterlist",
    "class/src/pluginparameter.js~PluginParameterList.html",
    "<span>PluginParameterList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginpiping",
    "class/src/pipeline.js~PluginPiping.html",
    "<span>PluginPiping</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~publicfeedlist",
    "class/src/feed.js~PublicFeedList.html",
    "<span>PublicFeedList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~request",
    "class/src/request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~requestexception",
    "class/src/exception.js~RequestException.html",
    "<span>RequestException</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~resource",
    "class/src/resource.js~Resource.html",
    "<span>Resource</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~servicefile",
    "class/src/servicefile.js~ServiceFile.html",
    "<span>ServiceFile</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~servicefilelist",
    "class/src/servicefile.js~ServiceFileList.html",
    "<span>ServiceFileList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~tag",
    "class/src/tag.js~Tag.html",
    "<span>Tag</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~tagfeedlist",
    "class/src/tag.js~TagFeedList.html",
    "<span>TagFeedList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~taglist",
    "class/src/tag.js~TagList.html",
    "<span>TagList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~tagtagginglist",
    "class/src/tag.js~TagTaggingList.html",
    "<span>TagTaggingList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~tagging",
    "class/src/tag.js~Tagging.html",
    "<span>Tagging</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~user",
    "class/src/user.js~User.html",
    "<span>User</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~userfile",
    "class/src/userfile.js~UserFile.html",
    "<span>UserFile</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~userfilelist",
    "class/src/userfile.js~UserFileList.html",
    "<span>UserFileList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~workflow",
    "class/src/workflow.js~Workflow.html",
    "<span>Workflow</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~workflowlist",
    "class/src/workflow.js~WorkflowList.html",
    "<span>WorkflowList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~workflowplugininstancelist",
    "class/src/plugininstance.js~WorkflowPluginInstanceList.html",
    "<span>WorkflowPluginInstanceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/admin.js",
    "file/src/admin.js.html",
    "src/admin.js",
    "file"
  ],
  [
    "src/admin.js~computeresourceadmin#constructor",
    "class/src/admin.js~ComputeResourceAdmin.html#instance-constructor-constructor",
    "src/admin.js~ComputeResourceAdmin#constructor",
    "method"
  ],
  [
    "src/admin.js~computeresourceadmin#delete",
    "class/src/admin.js~ComputeResourceAdmin.html#instance-method-delete",
    "src/admin.js~ComputeResourceAdmin#delete",
    "method"
  ],
  [
    "src/admin.js~computeresourceadminlist#constructor",
    "class/src/admin.js~ComputeResourceAdminList.html#instance-constructor-constructor",
    "src/admin.js~ComputeResourceAdminList#constructor",
    "method"
  ],
  [
    "src/admin.js~computeresourceadminlist#itemclass",
    "class/src/admin.js~ComputeResourceAdminList.html#instance-member-itemClass",
    "src/admin.js~ComputeResourceAdminList#itemClass",
    "member"
  ],
  [
    "src/admin.js~computeresourceadminlist#post",
    "class/src/admin.js~ComputeResourceAdminList.html#instance-method-post",
    "src/admin.js~ComputeResourceAdminList#post",
    "method"
  ],
  [
    "src/admin.js~pluginadmin#constructor",
    "class/src/admin.js~PluginAdmin.html#instance-constructor-constructor",
    "src/admin.js~PluginAdmin#constructor",
    "method"
  ],
  [
    "src/admin.js~pluginadmin#delete",
    "class/src/admin.js~PluginAdmin.html#instance-method-delete",
    "src/admin.js~PluginAdmin#delete",
    "method"
  ],
  [
    "src/admin.js~pluginadminlist#constructor",
    "class/src/admin.js~PluginAdminList.html#instance-constructor-constructor",
    "src/admin.js~PluginAdminList#constructor",
    "method"
  ],
  [
    "src/admin.js~pluginadminlist#getcomputeresourceadmins",
    "class/src/admin.js~PluginAdminList.html#instance-method-getComputeResourceAdmins",
    "src/admin.js~PluginAdminList#getComputeResourceAdmins",
    "method"
  ],
  [
    "src/admin.js~pluginadminlist#itemclass",
    "class/src/admin.js~PluginAdminList.html#instance-member-itemClass",
    "src/admin.js~PluginAdminList#itemClass",
    "member"
  ],
  [
    "src/admin.js~pluginadminlist#post",
    "class/src/admin.js~PluginAdminList.html#instance-method-post",
    "src/admin.js~PluginAdminList#post",
    "method"
  ],
  [
    "src/chrisinstance.js",
    "file/src/chrisinstance.js.html",
    "src/chrisinstance.js",
    "file"
  ],
  [
    "src/chrisinstance.js~chrisinstance#constructor",
    "class/src/chrisinstance.js~ChrisInstance.html#instance-constructor-constructor",
    "src/chrisinstance.js~ChrisInstance#constructor",
    "method"
  ],
  [
    "src/cj.js",
    "file/src/cj.js.html",
    "src/cj.js",
    "file"
  ],
  [
    "src/cj.js~collection.createcollectionobj",
    "class/src/cj.js~Collection.html#static-method-createCollectionObj",
    "src/cj.js~Collection.createCollectionObj",
    "method"
  ],
  [
    "src/cj.js~collection.geterrormessage",
    "class/src/cj.js~Collection.html#static-method-getErrorMessage",
    "src/cj.js~Collection.getErrorMessage",
    "method"
  ],
  [
    "src/cj.js~collection.getitemdescriptors",
    "class/src/cj.js~Collection.html#static-method-getItemDescriptors",
    "src/cj.js~Collection.getItemDescriptors",
    "method"
  ],
  [
    "src/cj.js~collection.getlinkrelationurls",
    "class/src/cj.js~Collection.html#static-method-getLinkRelationUrls",
    "src/cj.js~Collection.getLinkRelationUrls",
    "method"
  ],
  [
    "src/cj.js~collection.getqueryparameters",
    "class/src/cj.js~Collection.html#static-method-getQueryParameters",
    "src/cj.js~Collection.getQueryParameters",
    "method"
  ],
  [
    "src/cj.js~collection.gettemplatedescriptornames",
    "class/src/cj.js~Collection.html#static-method-getTemplateDescriptorNames",
    "src/cj.js~Collection.getTemplateDescriptorNames",
    "method"
  ],
  [
    "src/cj.js~collection.gettotalnumberofitems",
    "class/src/cj.js~Collection.html#static-method-getTotalNumberOfItems",
    "src/cj.js~Collection.getTotalNumberOfItems",
    "method"
  ],
  [
    "src/cj.js~collection.geturl",
    "class/src/cj.js~Collection.html#static-method-getUrl",
    "src/cj.js~Collection.getUrl",
    "method"
  ],
  [
    "src/cj.js~collection.maketemplate",
    "class/src/cj.js~Collection.html#static-method-makeTemplate",
    "src/cj.js~Collection.makeTemplate",
    "method"
  ],
  [
    "src/client.js",
    "file/src/client.js.html",
    "src/client.js",
    "file"
  ],
  [
    "src/client.js~client#_fetchres",
    "class/src/client.js~Client.html#instance-method-_fetchRes",
    "src/client.js~Client#_fetchRes",
    "method"
  ],
  [
    "src/client.js~client#adminuploadplugin",
    "class/src/client.js~Client.html#instance-method-adminUploadPlugin",
    "src/client.js~Client#adminUploadPlugin",
    "method"
  ],
  [
    "src/client.js~client#adminurl",
    "class/src/client.js~Client.html#instance-member-adminUrl",
    "src/client.js~Client#adminUrl",
    "member"
  ],
  [
    "src/client.js~client#auth",
    "class/src/client.js~Client.html#instance-member-auth",
    "src/client.js~Client#auth",
    "member"
  ],
  [
    "src/client.js~client#chrisinstanceurl",
    "class/src/client.js~Client.html#instance-member-chrisInstanceUrl",
    "src/client.js~Client#chrisInstanceUrl",
    "member"
  ],
  [
    "src/client.js~client#computeresourcesurl",
    "class/src/client.js~Client.html#instance-member-computeResourcesUrl",
    "src/client.js~Client#computeResourcesUrl",
    "member"
  ],
  [
    "src/client.js~client#computeworkflownodesinfo",
    "class/src/client.js~Client.html#instance-method-computeWorkflowNodesInfo",
    "src/client.js~Client#computeWorkflowNodesInfo",
    "method"
  ],
  [
    "src/client.js~client#constructor",
    "class/src/client.js~Client.html#instance-constructor-constructor",
    "src/client.js~Client#constructor",
    "method"
  ],
  [
    "src/client.js~client#createpipeline",
    "class/src/client.js~Client.html#instance-method-createPipeline",
    "src/client.js~Client#createPipeline",
    "method"
  ],
  [
    "src/client.js~client#createpipelineinstance",
    "class/src/client.js~Client.html#instance-method-createPipelineInstance",
    "src/client.js~Client#createPipelineInstance",
    "method"
  ],
  [
    "src/client.js~client#createplugininstance",
    "class/src/client.js~Client.html#instance-method-createPluginInstance",
    "src/client.js~Client#createPluginInstance",
    "method"
  ],
  [
    "src/client.js~client#createplugininstancesplit",
    "class/src/client.js~Client.html#instance-method-createPluginInstanceSplit",
    "src/client.js~Client#createPluginInstanceSplit",
    "method"
  ],
  [
    "src/client.js~client#createtag",
    "class/src/client.js~Client.html#instance-method-createTag",
    "src/client.js~Client#createTag",
    "method"
  ],
  [
    "src/client.js~client#createworkflow",
    "class/src/client.js~Client.html#instance-method-createWorkflow",
    "src/client.js~Client#createWorkflow",
    "method"
  ],
  [
    "src/client.js~client#feedsurl",
    "class/src/client.js~Client.html#instance-member-feedsUrl",
    "src/client.js~Client#feedsUrl",
    "member"
  ],
  [
    "src/client.js~client#filebrowserurl",
    "class/src/client.js~Client.html#instance-member-fileBrowserUrl",
    "src/client.js~Client#fileBrowserUrl",
    "member"
  ],
  [
    "src/client.js~client#getchrisinstance",
    "class/src/client.js~Client.html#instance-method-getChrisInstance",
    "src/client.js~Client#getChrisInstance",
    "method"
  ],
  [
    "src/client.js~client#getcomputeresource",
    "class/src/client.js~Client.html#instance-method-getComputeResource",
    "src/client.js~Client#getComputeResource",
    "method"
  ],
  [
    "src/client.js~client#getcomputeresources",
    "class/src/client.js~Client.html#instance-method-getComputeResources",
    "src/client.js~Client#getComputeResources",
    "method"
  ],
  [
    "src/client.js~client#getfeed",
    "class/src/client.js~Client.html#instance-method-getFeed",
    "src/client.js~Client#getFeed",
    "method"
  ],
  [
    "src/client.js~client#getfeeds",
    "class/src/client.js~Client.html#instance-method-getFeeds",
    "src/client.js~Client#getFeeds",
    "method"
  ],
  [
    "src/client.js~client#getfilebrowserfolder",
    "class/src/client.js~Client.html#instance-method-getFileBrowserFolder",
    "src/client.js~Client#getFileBrowserFolder",
    "method"
  ],
  [
    "src/client.js~client#getfilebrowserfolderbypath",
    "class/src/client.js~Client.html#instance-method-getFileBrowserFolderByPath",
    "src/client.js~Client#getFileBrowserFolderByPath",
    "method"
  ],
  [
    "src/client.js~client#getfilebrowserfolders",
    "class/src/client.js~Client.html#instance-method-getFileBrowserFolders",
    "src/client.js~Client#getFileBrowserFolders",
    "method"
  ],
  [
    "src/client.js~client#getpacsfile",
    "class/src/client.js~Client.html#instance-method-getPACSFile",
    "src/client.js~Client#getPACSFile",
    "method"
  ],
  [
    "src/client.js~client#getpacsfiles",
    "class/src/client.js~Client.html#instance-method-getPACSFiles",
    "src/client.js~Client#getPACSFiles",
    "method"
  ],
  [
    "src/client.js~client#getpipeline",
    "class/src/client.js~Client.html#instance-method-getPipeline",
    "src/client.js~Client#getPipeline",
    "method"
  ],
  [
    "src/client.js~client#getpipelineinstance",
    "class/src/client.js~Client.html#instance-method-getPipelineInstance",
    "src/client.js~Client#getPipelineInstance",
    "method"
  ],
  [
    "src/client.js~client#getpipelineinstances",
    "class/src/client.js~Client.html#instance-method-getPipelineInstances",
    "src/client.js~Client#getPipelineInstances",
    "method"
  ],
  [
    "src/client.js~client#getpipelinesourcefile",
    "class/src/client.js~Client.html#instance-method-getPipelineSourceFile",
    "src/client.js~Client#getPipelineSourceFile",
    "method"
  ],
  [
    "src/client.js~client#getpipelinesourcefiles",
    "class/src/client.js~Client.html#instance-method-getPipelineSourceFiles",
    "src/client.js~Client#getPipelineSourceFiles",
    "method"
  ],
  [
    "src/client.js~client#getpipelines",
    "class/src/client.js~Client.html#instance-method-getPipelines",
    "src/client.js~Client#getPipelines",
    "method"
  ],
  [
    "src/client.js~client#getplugin",
    "class/src/client.js~Client.html#instance-method-getPlugin",
    "src/client.js~Client#getPlugin",
    "method"
  ],
  [
    "src/client.js~client#getplugininstance",
    "class/src/client.js~Client.html#instance-method-getPluginInstance",
    "src/client.js~Client#getPluginInstance",
    "method"
  ],
  [
    "src/client.js~client#getplugininstances",
    "class/src/client.js~Client.html#instance-method-getPluginInstances",
    "src/client.js~Client#getPluginInstances",
    "method"
  ],
  [
    "src/client.js~client#getpluginmeta",
    "class/src/client.js~Client.html#instance-method-getPluginMeta",
    "src/client.js~Client#getPluginMeta",
    "method"
  ],
  [
    "src/client.js~client#getpluginmetas",
    "class/src/client.js~Client.html#instance-method-getPluginMetas",
    "src/client.js~Client#getPluginMetas",
    "method"
  ],
  [
    "src/client.js~client#getplugins",
    "class/src/client.js~Client.html#instance-method-getPlugins",
    "src/client.js~Client#getPlugins",
    "method"
  ],
  [
    "src/client.js~client#getpublicfeeds",
    "class/src/client.js~Client.html#instance-method-getPublicFeeds",
    "src/client.js~Client#getPublicFeeds",
    "method"
  ],
  [
    "src/client.js~client#getservicefile",
    "class/src/client.js~Client.html#instance-method-getServiceFile",
    "src/client.js~Client#getServiceFile",
    "method"
  ],
  [
    "src/client.js~client#getservicefiles",
    "class/src/client.js~Client.html#instance-method-getServiceFiles",
    "src/client.js~Client#getServiceFiles",
    "method"
  ],
  [
    "src/client.js~client#gettag",
    "class/src/client.js~Client.html#instance-method-getTag",
    "src/client.js~Client#getTag",
    "method"
  ],
  [
    "src/client.js~client#gettags",
    "class/src/client.js~Client.html#instance-method-getTags",
    "src/client.js~Client#getTags",
    "method"
  ],
  [
    "src/client.js~client#getuser",
    "class/src/client.js~Client.html#instance-method-getUser",
    "src/client.js~Client#getUser",
    "method"
  ],
  [
    "src/client.js~client#getuserfile",
    "class/src/client.js~Client.html#instance-method-getUserFile",
    "src/client.js~Client#getUserFile",
    "method"
  ],
  [
    "src/client.js~client#getuserfiles",
    "class/src/client.js~Client.html#instance-method-getUserFiles",
    "src/client.js~Client#getUserFiles",
    "method"
  ],
  [
    "src/client.js~client#getworkflow",
    "class/src/client.js~Client.html#instance-method-getWorkflow",
    "src/client.js~Client#getWorkflow",
    "method"
  ],
  [
    "src/client.js~client#getworkflows",
    "class/src/client.js~Client.html#instance-method-getWorkflows",
    "src/client.js~Client#getWorkflows",
    "method"
  ],
  [
    "src/client.js~client#pacsfilesurl",
    "class/src/client.js~Client.html#instance-member-pacsFilesUrl",
    "src/client.js~Client#pacsFilesUrl",
    "member"
  ],
  [
    "src/client.js~client#pipelineinstancesurl",
    "class/src/client.js~Client.html#instance-member-pipelineInstancesUrl",
    "src/client.js~Client#pipelineInstancesUrl",
    "member"
  ],
  [
    "src/client.js~client#pipelinesourcefilesurl",
    "class/src/client.js~Client.html#instance-member-pipelineSourceFilesUrl",
    "src/client.js~Client#pipelineSourceFilesUrl",
    "member"
  ],
  [
    "src/client.js~client#pipelinesurl",
    "class/src/client.js~Client.html#instance-member-pipelinesUrl",
    "src/client.js~Client#pipelinesUrl",
    "member"
  ],
  [
    "src/client.js~client#plugininstancesurl",
    "class/src/client.js~Client.html#instance-member-pluginInstancesUrl",
    "src/client.js~Client#pluginInstancesUrl",
    "member"
  ],
  [
    "src/client.js~client#pluginmetasurl",
    "class/src/client.js~Client.html#instance-member-pluginMetasUrl",
    "src/client.js~Client#pluginMetasUrl",
    "member"
  ],
  [
    "src/client.js~client#pluginsurl",
    "class/src/client.js~Client.html#instance-member-pluginsUrl",
    "src/client.js~Client#pluginsUrl",
    "member"
  ],
  [
    "src/client.js~client#publicfeedsurl",
    "class/src/client.js~Client.html#instance-member-publicFeedsUrl",
    "src/client.js~Client#publicFeedsUrl",
    "member"
  ],
  [
    "src/client.js~client#servicefilesurl",
    "class/src/client.js~Client.html#instance-member-serviceFilesUrl",
    "src/client.js~Client#serviceFilesUrl",
    "member"
  ],
  [
    "src/client.js~client#seturls",
    "class/src/client.js~Client.html#instance-method-setUrls",
    "src/client.js~Client#setUrls",
    "method"
  ],
  [
    "src/client.js~client#tagfeed",
    "class/src/client.js~Client.html#instance-method-tagFeed",
    "src/client.js~Client#tagFeed",
    "method"
  ],
  [
    "src/client.js~client#tagsurl",
    "class/src/client.js~Client.html#instance-member-tagsUrl",
    "src/client.js~Client#tagsUrl",
    "member"
  ],
  [
    "src/client.js~client#uploadfile",
    "class/src/client.js~Client.html#instance-method-uploadFile",
    "src/client.js~Client#uploadFile",
    "method"
  ],
  [
    "src/client.js~client#uploadpipelinesourcefile",
    "class/src/client.js~Client.html#instance-method-uploadPipelineSourceFile",
    "src/client.js~Client#uploadPipelineSourceFile",
    "method"
  ],
  [
    "src/client.js~client#url",
    "class/src/client.js~Client.html#instance-member-url",
    "src/client.js~Client#url",
    "member"
  ],
  [
    "src/client.js~client#userfilesurl",
    "class/src/client.js~Client.html#instance-member-userFilesUrl",
    "src/client.js~Client#userFilesUrl",
    "member"
  ],
  [
    "src/client.js~client#userurl",
    "class/src/client.js~Client.html#instance-member-userUrl",
    "src/client.js~Client#userUrl",
    "member"
  ],
  [
    "src/client.js~client#workflowsurl",
    "class/src/client.js~Client.html#instance-member-workflowsUrl",
    "src/client.js~Client#workflowsUrl",
    "member"
  ],
  [
    "src/client.js~client.createuser",
    "class/src/client.js~Client.html#static-method-createUser",
    "src/client.js~Client.createUser",
    "method"
  ],
  [
    "src/client.js~client.getauthtoken",
    "class/src/client.js~Client.html#static-method-getAuthToken",
    "src/client.js~Client.getAuthToken",
    "method"
  ],
  [
    "src/client.js~client.runasynctask",
    "class/src/client.js~Client.html#static-method-runAsyncTask",
    "src/client.js~Client.runAsyncTask",
    "method"
  ],
  [
    "src/comment.js",
    "file/src/comment.js.html",
    "src/comment.js",
    "file"
  ],
  [
    "src/comment.js~comment#constructor",
    "class/src/comment.js~Comment.html#instance-constructor-constructor",
    "src/comment.js~Comment#constructor",
    "method"
  ],
  [
    "src/comment.js~comment#delete",
    "class/src/comment.js~Comment.html#instance-method-delete",
    "src/comment.js~Comment#delete",
    "method"
  ],
  [
    "src/comment.js~comment#getfeed",
    "class/src/comment.js~Comment.html#instance-method-getFeed",
    "src/comment.js~Comment#getFeed",
    "method"
  ],
  [
    "src/comment.js~comment#put",
    "class/src/comment.js~Comment.html#instance-method-put",
    "src/comment.js~Comment#put",
    "method"
  ],
  [
    "src/comment.js~commentlist#constructor",
    "class/src/comment.js~CommentList.html#instance-constructor-constructor",
    "src/comment.js~CommentList#constructor",
    "method"
  ],
  [
    "src/comment.js~commentlist#getfeed",
    "class/src/comment.js~CommentList.html#instance-method-getFeed",
    "src/comment.js~CommentList#getFeed",
    "method"
  ],
  [
    "src/comment.js~commentlist#itemclass",
    "class/src/comment.js~CommentList.html#instance-member-itemClass",
    "src/comment.js~CommentList#itemClass",
    "member"
  ],
  [
    "src/comment.js~commentlist#post",
    "class/src/comment.js~CommentList.html#instance-method-post",
    "src/comment.js~CommentList#post",
    "method"
  ],
  [
    "src/computeresource.js",
    "file/src/computeresource.js.html",
    "src/computeresource.js",
    "file"
  ],
  [
    "src/computeresource.js~computeresource#constructor",
    "class/src/computeresource.js~ComputeResource.html#instance-constructor-constructor",
    "src/computeresource.js~ComputeResource#constructor",
    "method"
  ],
  [
    "src/computeresource.js~computeresourcelist#constructor",
    "class/src/computeresource.js~ComputeResourceList.html#instance-constructor-constructor",
    "src/computeresource.js~ComputeResourceList#constructor",
    "method"
  ],
  [
    "src/computeresource.js~computeresourcelist#getfeeds",
    "class/src/computeresource.js~ComputeResourceList.html#instance-method-getFeeds",
    "src/computeresource.js~ComputeResourceList#getFeeds",
    "method"
  ],
  [
    "src/computeresource.js~computeresourcelist#itemclass",
    "class/src/computeresource.js~ComputeResourceList.html#instance-member-itemClass",
    "src/computeresource.js~ComputeResourceList#itemClass",
    "member"
  ],
  [
    "src/computeresource.js~plugincomputeresourcelist#constructor",
    "class/src/computeresource.js~PluginComputeResourceList.html#instance-constructor-constructor",
    "src/computeresource.js~PluginComputeResourceList#constructor",
    "method"
  ],
  [
    "src/computeresource.js~plugincomputeresourcelist#getplugin",
    "class/src/computeresource.js~PluginComputeResourceList.html#instance-method-getPlugin",
    "src/computeresource.js~PluginComputeResourceList#getPlugin",
    "method"
  ],
  [
    "src/computeresource.js~plugincomputeresourcelist#itemclass",
    "class/src/computeresource.js~PluginComputeResourceList.html#instance-member-itemClass",
    "src/computeresource.js~PluginComputeResourceList#itemClass",
    "member"
  ],
  [
    "src/exception.js",
    "file/src/exception.js.html",
    "src/exception.js",
    "file"
  ],
  [
    "src/exception.js~requestexception#constructor",
    "class/src/exception.js~RequestException.html#instance-constructor-constructor",
    "src/exception.js~RequestException#constructor",
    "method"
  ],
  [
    "src/exception.js~requestexception#name",
    "class/src/exception.js~RequestException.html#instance-member-name",
    "src/exception.js~RequestException#name",
    "member"
  ],
  [
    "src/exception.js~requestexception#request",
    "class/src/exception.js~RequestException.html#instance-member-request",
    "src/exception.js~RequestException#request",
    "member"
  ],
  [
    "src/exception.js~requestexception#response",
    "class/src/exception.js~RequestException.html#instance-member-response",
    "src/exception.js~RequestException#response",
    "member"
  ],
  [
    "src/feed.js",
    "file/src/feed.js.html",
    "src/feed.js",
    "file"
  ],
  [
    "src/feed.js~feed#delete",
    "class/src/feed.js~Feed.html#instance-method-delete",
    "src/feed.js~Feed#delete",
    "method"
  ],
  [
    "src/feed.js~feed#getcomment",
    "class/src/feed.js~Feed.html#instance-method-getComment",
    "src/feed.js~Feed#getComment",
    "method"
  ],
  [
    "src/feed.js~feed#getcomments",
    "class/src/feed.js~Feed.html#instance-method-getComments",
    "src/feed.js~Feed#getComments",
    "method"
  ],
  [
    "src/feed.js~feed#getnote",
    "class/src/feed.js~Feed.html#instance-method-getNote",
    "src/feed.js~Feed#getNote",
    "method"
  ],
  [
    "src/feed.js~feed#getplugininstances",
    "class/src/feed.js~Feed.html#instance-method-getPluginInstances",
    "src/feed.js~Feed#getPluginInstances",
    "method"
  ],
  [
    "src/feed.js~feed#gettaggings",
    "class/src/feed.js~Feed.html#instance-method-getTaggings",
    "src/feed.js~Feed#getTaggings",
    "method"
  ],
  [
    "src/feed.js~feed#gettags",
    "class/src/feed.js~Feed.html#instance-method-getTags",
    "src/feed.js~Feed#getTags",
    "method"
  ],
  [
    "src/feed.js~feed#put",
    "class/src/feed.js~Feed.html#instance-method-put",
    "src/feed.js~Feed#put",
    "method"
  ],
  [
    "src/feed.js~feed#tagfeed",
    "class/src/feed.js~Feed.html#instance-method-tagFeed",
    "src/feed.js~Feed#tagFeed",
    "method"
  ],
  [
    "src/feed.js~feedlist#constructor",
    "class/src/feed.js~FeedList.html#instance-constructor-constructor",
    "src/feed.js~FeedList#constructor",
    "method"
  ],
  [
    "src/feed.js~feedlist#getchrisinstance",
    "class/src/feed.js~FeedList.html#instance-method-getChrisInstance",
    "src/feed.js~FeedList#getChrisInstance",
    "method"
  ],
  [
    "src/feed.js~feedlist#getcomputeresources",
    "class/src/feed.js~FeedList.html#instance-method-getComputeResources",
    "src/feed.js~FeedList#getComputeResources",
    "method"
  ],
  [
    "src/feed.js~feedlist#getfilebrowserfolders",
    "class/src/feed.js~FeedList.html#instance-method-getFileBrowserFolders",
    "src/feed.js~FeedList#getFileBrowserFolders",
    "method"
  ],
  [
    "src/feed.js~feedlist#getpacsfiles",
    "class/src/feed.js~FeedList.html#instance-method-getPACSFiles",
    "src/feed.js~FeedList#getPACSFiles",
    "method"
  ],
  [
    "src/feed.js~feedlist#getpipelineinstances",
    "class/src/feed.js~FeedList.html#instance-method-getPipelineInstances",
    "src/feed.js~FeedList#getPipelineInstances",
    "method"
  ],
  [
    "src/feed.js~feedlist#getpipelinesourcefiles",
    "class/src/feed.js~FeedList.html#instance-method-getPipelineSourceFiles",
    "src/feed.js~FeedList#getPipelineSourceFiles",
    "method"
  ],
  [
    "src/feed.js~feedlist#getpipelines",
    "class/src/feed.js~FeedList.html#instance-method-getPipelines",
    "src/feed.js~FeedList#getPipelines",
    "method"
  ],
  [
    "src/feed.js~feedlist#getpluginadmins",
    "class/src/feed.js~FeedList.html#instance-method-getPluginAdmins",
    "src/feed.js~FeedList#getPluginAdmins",
    "method"
  ],
  [
    "src/feed.js~feedlist#getplugininstances",
    "class/src/feed.js~FeedList.html#instance-method-getPluginInstances",
    "src/feed.js~FeedList#getPluginInstances",
    "method"
  ],
  [
    "src/feed.js~feedlist#getplugins",
    "class/src/feed.js~FeedList.html#instance-method-getPlugins",
    "src/feed.js~FeedList#getPlugins",
    "method"
  ],
  [
    "src/feed.js~feedlist#getpublicfeeds",
    "class/src/feed.js~FeedList.html#instance-method-getPublicFeeds",
    "src/feed.js~FeedList#getPublicFeeds",
    "method"
  ],
  [
    "src/feed.js~feedlist#getservicefiles",
    "class/src/feed.js~FeedList.html#instance-method-getServiceFiles",
    "src/feed.js~FeedList#getServiceFiles",
    "method"
  ],
  [
    "src/feed.js~feedlist#gettags",
    "class/src/feed.js~FeedList.html#instance-method-getTags",
    "src/feed.js~FeedList#getTags",
    "method"
  ],
  [
    "src/feed.js~feedlist#getuser",
    "class/src/feed.js~FeedList.html#instance-method-getUser",
    "src/feed.js~FeedList#getUser",
    "method"
  ],
  [
    "src/feed.js~feedlist#getuserfiles",
    "class/src/feed.js~FeedList.html#instance-method-getUserFiles",
    "src/feed.js~FeedList#getUserFiles",
    "method"
  ],
  [
    "src/feed.js~feedlist#itemclass",
    "class/src/feed.js~FeedList.html#instance-member-itemClass",
    "src/feed.js~FeedList#itemClass",
    "member"
  ],
  [
    "src/feed.js~publicfeedlist#constructor",
    "class/src/feed.js~PublicFeedList.html#instance-constructor-constructor",
    "src/feed.js~PublicFeedList#constructor",
    "method"
  ],
  [
    "src/feed.js~publicfeedlist#itemclass",
    "class/src/feed.js~PublicFeedList.html#instance-member-itemClass",
    "src/feed.js~PublicFeedList#itemClass",
    "member"
  ],
  [
    "src/filebrowser.js",
    "file/src/filebrowser.js.html",
    "src/filebrowser.js",
    "file"
  ],
  [
    "src/filebrowser.js~filebrowserfolder#getchildren",
    "class/src/filebrowser.js~FileBrowserFolder.html#instance-method-getChildren",
    "src/filebrowser.js~FileBrowserFolder#getChildren",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolder#getfiles",
    "class/src/filebrowser.js~FileBrowserFolder.html#instance-method-getFiles",
    "src/filebrowser.js~FileBrowserFolder#getFiles",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolder#getlinkfiles",
    "class/src/filebrowser.js~FileBrowserFolder.html#instance-method-getLinkFiles",
    "src/filebrowser.js~FileBrowserFolder#getLinkFiles",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolder#getparent",
    "class/src/filebrowser.js~FileBrowserFolder.html#instance-method-getParent",
    "src/filebrowser.js~FileBrowserFolder#getParent",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderchildlist#constructor",
    "class/src/filebrowser.js~FileBrowserFolderChildList.html#instance-constructor-constructor",
    "src/filebrowser.js~FileBrowserFolderChildList#constructor",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderchildlist#itemclass",
    "class/src/filebrowser.js~FileBrowserFolderChildList.html#instance-member-itemClass",
    "src/filebrowser.js~FileBrowserFolderChildList#itemClass",
    "member"
  ],
  [
    "src/filebrowser.js~filebrowserfolderfile#getfileblob",
    "class/src/filebrowser.js~FileBrowserFolderFile.html#instance-method-getFileBlob",
    "src/filebrowser.js~FileBrowserFolderFile#getFileBlob",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderfile#getparentfolder",
    "class/src/filebrowser.js~FileBrowserFolderFile.html#instance-method-getParentFolder",
    "src/filebrowser.js~FileBrowserFolderFile#getParentFolder",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderfilelist#constructor",
    "class/src/filebrowser.js~FileBrowserFolderFileList.html#instance-constructor-constructor",
    "src/filebrowser.js~FileBrowserFolderFileList#constructor",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderfilelist#itemclass",
    "class/src/filebrowser.js~FileBrowserFolderFileList.html#instance-member-itemClass",
    "src/filebrowser.js~FileBrowserFolderFileList#itemClass",
    "member"
  ],
  [
    "src/filebrowser.js~filebrowserfolderlinkfile#getfileblob",
    "class/src/filebrowser.js~FileBrowserFolderLinkFile.html#instance-method-getFileBlob",
    "src/filebrowser.js~FileBrowserFolderLinkFile#getFileBlob",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderlinkfile#getlinkedresource",
    "class/src/filebrowser.js~FileBrowserFolderLinkFile.html#instance-method-getLinkedResource",
    "src/filebrowser.js~FileBrowserFolderLinkFile#getLinkedResource",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderlinkfile#getparentfolder",
    "class/src/filebrowser.js~FileBrowserFolderLinkFile.html#instance-method-getParentFolder",
    "src/filebrowser.js~FileBrowserFolderLinkFile#getParentFolder",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderlinkfilelist#constructor",
    "class/src/filebrowser.js~FileBrowserFolderLinkFileList.html#instance-constructor-constructor",
    "src/filebrowser.js~FileBrowserFolderLinkFileList#constructor",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderlinkfilelist#itemclass",
    "class/src/filebrowser.js~FileBrowserFolderLinkFileList.html#instance-member-itemClass",
    "src/filebrowser.js~FileBrowserFolderLinkFileList#itemClass",
    "member"
  ],
  [
    "src/filebrowser.js~filebrowserfolderlist#constructor",
    "class/src/filebrowser.js~FileBrowserFolderList.html#instance-constructor-constructor",
    "src/filebrowser.js~FileBrowserFolderList#constructor",
    "method"
  ],
  [
    "src/filebrowser.js~filebrowserfolderlist#itemclass",
    "class/src/filebrowser.js~FileBrowserFolderList.html#instance-member-itemClass",
    "src/filebrowser.js~FileBrowserFolderList#itemClass",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/note.js",
    "file/src/note.js.html",
    "src/note.js",
    "file"
  ],
  [
    "src/note.js~note#put",
    "class/src/note.js~Note.html#instance-method-put",
    "src/note.js~Note#put",
    "method"
  ],
  [
    "src/pacsfile.js",
    "file/src/pacsfile.js.html",
    "src/pacsfile.js",
    "file"
  ],
  [
    "src/pacsfile.js~pacsfile#constructor",
    "class/src/pacsfile.js~PACSFile.html#instance-constructor-constructor",
    "src/pacsfile.js~PACSFile#constructor",
    "method"
  ],
  [
    "src/pacsfile.js~pacsfile#getfileblob",
    "class/src/pacsfile.js~PACSFile.html#instance-method-getFileBlob",
    "src/pacsfile.js~PACSFile#getFileBlob",
    "method"
  ],
  [
    "src/pacsfile.js~pacsfile#getparentfolder",
    "class/src/pacsfile.js~PACSFile.html#instance-method-getParentFolder",
    "src/pacsfile.js~PACSFile#getParentFolder",
    "method"
  ],
  [
    "src/pacsfile.js~pacsfilelist#constructor",
    "class/src/pacsfile.js~PACSFileList.html#instance-constructor-constructor",
    "src/pacsfile.js~PACSFileList#constructor",
    "method"
  ],
  [
    "src/pacsfile.js~pacsfilelist#itemclass",
    "class/src/pacsfile.js~PACSFileList.html#instance-member-itemClass",
    "src/pacsfile.js~PACSFileList#itemClass",
    "member"
  ],
  [
    "src/pipeline.js",
    "file/src/pipeline.js.html",
    "src/pipeline.js",
    "file"
  ],
  [
    "src/pipeline.js~pipeline#delete",
    "class/src/pipeline.js~Pipeline.html#instance-method-delete",
    "src/pipeline.js~Pipeline#delete",
    "method"
  ],
  [
    "src/pipeline.js~pipeline#getdefaultparameters",
    "class/src/pipeline.js~Pipeline.html#instance-method-getDefaultParameters",
    "src/pipeline.js~Pipeline#getDefaultParameters",
    "method"
  ],
  [
    "src/pipeline.js~pipeline#getpipelineinstances",
    "class/src/pipeline.js~Pipeline.html#instance-method-getPipelineInstances",
    "src/pipeline.js~Pipeline#getPipelineInstances",
    "method"
  ],
  [
    "src/pipeline.js~pipeline#getpipelinesourcefile",
    "class/src/pipeline.js~Pipeline.html#instance-method-getPipelineSourceFile",
    "src/pipeline.js~Pipeline#getPipelineSourceFile",
    "method"
  ],
  [
    "src/pipeline.js~pipeline#getpluginpipings",
    "class/src/pipeline.js~Pipeline.html#instance-method-getPluginPipings",
    "src/pipeline.js~Pipeline#getPluginPipings",
    "method"
  ],
  [
    "src/pipeline.js~pipeline#getplugins",
    "class/src/pipeline.js~Pipeline.html#instance-method-getPlugins",
    "src/pipeline.js~Pipeline#getPlugins",
    "method"
  ],
  [
    "src/pipeline.js~pipeline#getworkflows",
    "class/src/pipeline.js~Pipeline.html#instance-method-getWorkflows",
    "src/pipeline.js~Pipeline#getWorkflows",
    "method"
  ],
  [
    "src/pipeline.js~pipeline#put",
    "class/src/pipeline.js~Pipeline.html#instance-method-put",
    "src/pipeline.js~Pipeline#put",
    "method"
  ],
  [
    "src/pipeline.js~pipelinelist#constructor",
    "class/src/pipeline.js~PipelineList.html#instance-constructor-constructor",
    "src/pipeline.js~PipelineList#constructor",
    "method"
  ],
  [
    "src/pipeline.js~pipelinelist#getplugins",
    "class/src/pipeline.js~PipelineList.html#instance-method-getPlugins",
    "src/pipeline.js~PipelineList#getPlugins",
    "method"
  ],
  [
    "src/pipeline.js~pipelinelist#itemclass",
    "class/src/pipeline.js~PipelineList.html#instance-member-itemClass",
    "src/pipeline.js~PipelineList#itemClass",
    "member"
  ],
  [
    "src/pipeline.js~pipelinelist#post",
    "class/src/pipeline.js~PipelineList.html#instance-method-post",
    "src/pipeline.js~PipelineList#post",
    "method"
  ],
  [
    "src/pipeline.js~pipelinepipingdefaultparameterlist#constructor",
    "class/src/pipeline.js~PipelinePipingDefaultParameterList.html#instance-constructor-constructor",
    "src/pipeline.js~PipelinePipingDefaultParameterList#constructor",
    "method"
  ],
  [
    "src/pipeline.js~pipelinepipingdefaultparameterlist#itemclass",
    "class/src/pipeline.js~PipelinePipingDefaultParameterList.html#instance-member-itemClass",
    "src/pipeline.js~PipelinePipingDefaultParameterList#itemClass",
    "member"
  ],
  [
    "src/pipeline.js~pipelinepluginlist#constructor",
    "class/src/pipeline.js~PipelinePluginList.html#instance-constructor-constructor",
    "src/pipeline.js~PipelinePluginList#constructor",
    "method"
  ],
  [
    "src/pipeline.js~pipelinepluginlist#itemclass",
    "class/src/pipeline.js~PipelinePluginList.html#instance-member-itemClass",
    "src/pipeline.js~PipelinePluginList#itemClass",
    "member"
  ],
  [
    "src/pipeline.js~pipelinepluginpipinglist#constructor",
    "class/src/pipeline.js~PipelinePluginPipingList.html#instance-constructor-constructor",
    "src/pipeline.js~PipelinePluginPipingList#constructor",
    "method"
  ],
  [
    "src/pipeline.js~pipelinepluginpipinglist#itemclass",
    "class/src/pipeline.js~PipelinePluginPipingList.html#instance-member-itemClass",
    "src/pipeline.js~PipelinePluginPipingList#itemClass",
    "member"
  ],
  [
    "src/pipeline.js~pipelinesourcefile#getfileblob",
    "class/src/pipeline.js~PipelineSourceFile.html#instance-method-getFileBlob",
    "src/pipeline.js~PipelineSourceFile#getFileBlob",
    "method"
  ],
  [
    "src/pipeline.js~pipelinesourcefile#getparentfolder",
    "class/src/pipeline.js~PipelineSourceFile.html#instance-method-getParentFolder",
    "src/pipeline.js~PipelineSourceFile#getParentFolder",
    "method"
  ],
  [
    "src/pipeline.js~pipelinesourcefile#getpipeline",
    "class/src/pipeline.js~PipelineSourceFile.html#instance-method-getPipeline",
    "src/pipeline.js~PipelineSourceFile#getPipeline",
    "method"
  ],
  [
    "src/pipeline.js~pipelinesourcefilelist#constructor",
    "class/src/pipeline.js~PipelineSourceFileList.html#instance-constructor-constructor",
    "src/pipeline.js~PipelineSourceFileList#constructor",
    "method"
  ],
  [
    "src/pipeline.js~pipelinesourcefilelist#itemclass",
    "class/src/pipeline.js~PipelineSourceFileList.html#instance-member-itemClass",
    "src/pipeline.js~PipelineSourceFileList#itemClass",
    "member"
  ],
  [
    "src/pipeline.js~pipelinesourcefilelist#post",
    "class/src/pipeline.js~PipelineSourceFileList.html#instance-method-post",
    "src/pipeline.js~PipelineSourceFileList#post",
    "method"
  ],
  [
    "src/pipeline.js~pipingdefaultparameter#getpluginparameter",
    "class/src/pipeline.js~PipingDefaultParameter.html#instance-method-getPluginParameter",
    "src/pipeline.js~PipingDefaultParameter#getPluginParameter",
    "method"
  ],
  [
    "src/pipeline.js~pipingdefaultparameter#getpluginpiping",
    "class/src/pipeline.js~PipingDefaultParameter.html#instance-method-getPluginPiping",
    "src/pipeline.js~PipingDefaultParameter#getPluginPiping",
    "method"
  ],
  [
    "src/pipeline.js~pluginpiping#getpipeline",
    "class/src/pipeline.js~PluginPiping.html#instance-method-getPipeline",
    "src/pipeline.js~PluginPiping#getPipeline",
    "method"
  ],
  [
    "src/pipeline.js~pluginpiping#getplugin",
    "class/src/pipeline.js~PluginPiping.html#instance-method-getPlugin",
    "src/pipeline.js~PluginPiping#getPlugin",
    "method"
  ],
  [
    "src/pipeline.js~pluginpiping#getpreviouspluginpiping",
    "class/src/pipeline.js~PluginPiping.html#instance-method-getPreviousPluginPiping",
    "src/pipeline.js~PluginPiping#getPreviousPluginPiping",
    "method"
  ],
  [
    "src/pipelineinstance.js",
    "file/src/pipelineinstance.js.html",
    "src/pipelineinstance.js",
    "file"
  ],
  [
    "src/pipelineinstance.js~allpipelineinstancelist#constructor",
    "class/src/pipelineinstance.js~AllPipelineInstanceList.html#instance-constructor-constructor",
    "src/pipelineinstance.js~AllPipelineInstanceList#constructor",
    "method"
  ],
  [
    "src/pipelineinstance.js~allpipelineinstancelist#getpipelines",
    "class/src/pipelineinstance.js~AllPipelineInstanceList.html#instance-method-getPipelines",
    "src/pipelineinstance.js~AllPipelineInstanceList#getPipelines",
    "method"
  ],
  [
    "src/pipelineinstance.js~allpipelineinstancelist#itemclass",
    "class/src/pipelineinstance.js~AllPipelineInstanceList.html#instance-member-itemClass",
    "src/pipelineinstance.js~AllPipelineInstanceList#itemClass",
    "member"
  ],
  [
    "src/pipelineinstance.js~pipelineinstance#constructor",
    "class/src/pipelineinstance.js~PipelineInstance.html#instance-constructor-constructor",
    "src/pipelineinstance.js~PipelineInstance#constructor",
    "method"
  ],
  [
    "src/pipelineinstance.js~pipelineinstance#delete",
    "class/src/pipelineinstance.js~PipelineInstance.html#instance-method-delete",
    "src/pipelineinstance.js~PipelineInstance#delete",
    "method"
  ],
  [
    "src/pipelineinstance.js~pipelineinstance#getpipeline",
    "class/src/pipelineinstance.js~PipelineInstance.html#instance-method-getPipeline",
    "src/pipelineinstance.js~PipelineInstance#getPipeline",
    "method"
  ],
  [
    "src/pipelineinstance.js~pipelineinstance#getplugininstances",
    "class/src/pipelineinstance.js~PipelineInstance.html#instance-method-getPluginInstances",
    "src/pipelineinstance.js~PipelineInstance#getPluginInstances",
    "method"
  ],
  [
    "src/pipelineinstance.js~pipelineinstance#put",
    "class/src/pipelineinstance.js~PipelineInstance.html#instance-method-put",
    "src/pipelineinstance.js~PipelineInstance#put",
    "method"
  ],
  [
    "src/pipelineinstance.js~pipelineinstancelist#constructor",
    "class/src/pipelineinstance.js~PipelineInstanceList.html#instance-constructor-constructor",
    "src/pipelineinstance.js~PipelineInstanceList#constructor",
    "method"
  ],
  [
    "src/pipelineinstance.js~pipelineinstancelist#itemclass",
    "class/src/pipelineinstance.js~PipelineInstanceList.html#instance-member-itemClass",
    "src/pipelineinstance.js~PipelineInstanceList#itemClass",
    "member"
  ],
  [
    "src/pipelineinstance.js~pipelineinstancelist#post",
    "class/src/pipelineinstance.js~PipelineInstanceList.html#instance-method-post",
    "src/pipelineinstance.js~PipelineInstanceList#post",
    "method"
  ],
  [
    "src/plugin.js",
    "file/src/plugin.js.html",
    "src/plugin.js",
    "file"
  ],
  [
    "src/plugin.js~plugin#getplugincomputeresources",
    "class/src/plugin.js~Plugin.html#instance-method-getPluginComputeResources",
    "src/plugin.js~Plugin#getPluginComputeResources",
    "method"
  ],
  [
    "src/plugin.js~plugin#getplugininstances",
    "class/src/plugin.js~Plugin.html#instance-method-getPluginInstances",
    "src/plugin.js~Plugin#getPluginInstances",
    "method"
  ],
  [
    "src/plugin.js~plugin#getpluginmeta",
    "class/src/plugin.js~Plugin.html#instance-method-getPluginMeta",
    "src/plugin.js~Plugin#getPluginMeta",
    "method"
  ],
  [
    "src/plugin.js~plugin#getpluginparameters",
    "class/src/plugin.js~Plugin.html#instance-method-getPluginParameters",
    "src/plugin.js~Plugin#getPluginParameters",
    "method"
  ],
  [
    "src/plugin.js~pluginlist#constructor",
    "class/src/plugin.js~PluginList.html#instance-constructor-constructor",
    "src/plugin.js~PluginList#constructor",
    "method"
  ],
  [
    "src/plugin.js~pluginlist#getfeeds",
    "class/src/plugin.js~PluginList.html#instance-method-getFeeds",
    "src/plugin.js~PluginList#getFeeds",
    "method"
  ],
  [
    "src/plugin.js~pluginlist#itemclass",
    "class/src/plugin.js~PluginList.html#instance-member-itemClass",
    "src/plugin.js~PluginList#itemClass",
    "member"
  ],
  [
    "src/plugin.js~pluginmetapluginlist#constructor",
    "class/src/plugin.js~PluginMetaPluginList.html#instance-constructor-constructor",
    "src/plugin.js~PluginMetaPluginList#constructor",
    "method"
  ],
  [
    "src/plugin.js~pluginmetapluginlist#getpluginmeta",
    "class/src/plugin.js~PluginMetaPluginList.html#instance-method-getPluginMeta",
    "src/plugin.js~PluginMetaPluginList#getPluginMeta",
    "method"
  ],
  [
    "src/plugin.js~pluginmetapluginlist#itemclass",
    "class/src/plugin.js~PluginMetaPluginList.html#instance-member-itemClass",
    "src/plugin.js~PluginMetaPluginList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js",
    "file/src/plugininstance.js.html",
    "src/plugininstance.js",
    "file"
  ],
  [
    "src/plugininstance.js~allplugininstancelist#constructor",
    "class/src/plugininstance.js~AllPluginInstanceList.html#instance-constructor-constructor",
    "src/plugininstance.js~AllPluginInstanceList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~allplugininstancelist#getplugins",
    "class/src/plugininstance.js~AllPluginInstanceList.html#instance-method-getPlugins",
    "src/plugininstance.js~AllPluginInstanceList#getPlugins",
    "method"
  ],
  [
    "src/plugininstance.js~allplugininstancelist#itemclass",
    "class/src/plugininstance.js~AllPluginInstanceList.html#instance-member-itemClass",
    "src/plugininstance.js~AllPluginInstanceList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~feedplugininstancelist#constructor",
    "class/src/plugininstance.js~FeedPluginInstanceList.html#instance-constructor-constructor",
    "src/plugininstance.js~FeedPluginInstanceList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~feedplugininstancelist#getfeed",
    "class/src/plugininstance.js~FeedPluginInstanceList.html#instance-method-getFeed",
    "src/plugininstance.js~FeedPluginInstanceList#getFeed",
    "method"
  ],
  [
    "src/plugininstance.js~feedplugininstancelist#itemclass",
    "class/src/plugininstance.js~FeedPluginInstanceList.html#instance-member-itemClass",
    "src/plugininstance.js~FeedPluginInstanceList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~pipelineinstanceplugininstancelist#constructor",
    "class/src/plugininstance.js~PipelineInstancePluginInstanceList.html#instance-constructor-constructor",
    "src/plugininstance.js~PipelineInstancePluginInstanceList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~pipelineinstanceplugininstancelist#itemclass",
    "class/src/plugininstance.js~PipelineInstancePluginInstanceList.html#instance-member-itemClass",
    "src/plugininstance.js~PipelineInstancePluginInstanceList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~plugininstance#delete",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-delete",
    "src/plugininstance.js~PluginInstance#delete",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getcomputeresource",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getComputeResource",
    "src/plugininstance.js~PluginInstance#getComputeResource",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getdescendantplugininstances",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getDescendantPluginInstances",
    "src/plugininstance.js~PluginInstance#getDescendantPluginInstances",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getfeed",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getFeed",
    "src/plugininstance.js~PluginInstance#getFeed",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getoutputfolder",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getOutputFolder",
    "src/plugininstance.js~PluginInstance#getOutputFolder",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getparameters",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getParameters",
    "src/plugininstance.js~PluginInstance#getParameters",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getpipelineinstance",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getPipelineInstance",
    "src/plugininstance.js~PluginInstance#getPipelineInstance",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getplugin",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getPlugin",
    "src/plugininstance.js~PluginInstance#getPlugin",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getpreviousplugininstance",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getPreviousPluginInstance",
    "src/plugininstance.js~PluginInstance#getPreviousPluginInstance",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getsplits",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getSplits",
    "src/plugininstance.js~PluginInstance#getSplits",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getworkflow",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getWorkflow",
    "src/plugininstance.js~PluginInstance#getWorkflow",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#put",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-put",
    "src/plugininstance.js~PluginInstance#put",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancedescendantlist#constructor",
    "class/src/plugininstance.js~PluginInstanceDescendantList.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstanceDescendantList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancedescendantlist#itemclass",
    "class/src/plugininstance.js~PluginInstanceDescendantList.html#instance-member-itemClass",
    "src/plugininstance.js~PluginInstanceDescendantList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~plugininstancelist#constructor",
    "class/src/plugininstance.js~PluginInstanceList.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstanceList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancelist#getplugin",
    "class/src/plugininstance.js~PluginInstanceList.html#instance-method-getPlugin",
    "src/plugininstance.js~PluginInstanceList#getPlugin",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancelist#itemclass",
    "class/src/plugininstance.js~PluginInstanceList.html#instance-member-itemClass",
    "src/plugininstance.js~PluginInstanceList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~plugininstancelist#post",
    "class/src/plugininstance.js~PluginInstanceList.html#instance-method-post",
    "src/plugininstance.js~PluginInstanceList#post",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstanceparameter#getplugininstance",
    "class/src/plugininstance.js~PluginInstanceParameter.html#instance-method-getPluginInstance",
    "src/plugininstance.js~PluginInstanceParameter#getPluginInstance",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstanceparameter#getpluginparameter",
    "class/src/plugininstance.js~PluginInstanceParameter.html#instance-method-getPluginParameter",
    "src/plugininstance.js~PluginInstanceParameter#getPluginParameter",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstanceparameterlist#constructor",
    "class/src/plugininstance.js~PluginInstanceParameterList.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstanceParameterList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstanceparameterlist#itemclass",
    "class/src/plugininstance.js~PluginInstanceParameterList.html#instance-member-itemClass",
    "src/plugininstance.js~PluginInstanceParameterList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~plugininstancesplit#constructor",
    "class/src/plugininstance.js~PluginInstanceSplit.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstanceSplit#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancesplit#getplugininstance",
    "class/src/plugininstance.js~PluginInstanceSplit.html#instance-method-getPluginInstance",
    "src/plugininstance.js~PluginInstanceSplit#getPluginInstance",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancesplitlist#constructor",
    "class/src/plugininstance.js~PluginInstanceSplitList.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstanceSplitList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancesplitlist#getplugininstance",
    "class/src/plugininstance.js~PluginInstanceSplitList.html#instance-method-getPluginInstance",
    "src/plugininstance.js~PluginInstanceSplitList#getPluginInstance",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancesplitlist#itemclass",
    "class/src/plugininstance.js~PluginInstanceSplitList.html#instance-member-itemClass",
    "src/plugininstance.js~PluginInstanceSplitList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~plugininstancesplitlist#post",
    "class/src/plugininstance.js~PluginInstanceSplitList.html#instance-method-post",
    "src/plugininstance.js~PluginInstanceSplitList#post",
    "method"
  ],
  [
    "src/plugininstance.js~workflowplugininstancelist#constructor",
    "class/src/plugininstance.js~WorkflowPluginInstanceList.html#instance-constructor-constructor",
    "src/plugininstance.js~WorkflowPluginInstanceList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~workflowplugininstancelist#itemclass",
    "class/src/plugininstance.js~WorkflowPluginInstanceList.html#instance-member-itemClass",
    "src/plugininstance.js~WorkflowPluginInstanceList#itemClass",
    "member"
  ],
  [
    "src/pluginmeta.js",
    "file/src/pluginmeta.js.html",
    "src/pluginmeta.js",
    "file"
  ],
  [
    "src/pluginmeta.js~pluginmeta#getplugins",
    "class/src/pluginmeta.js~PluginMeta.html#instance-method-getPlugins",
    "src/pluginmeta.js~PluginMeta#getPlugins",
    "method"
  ],
  [
    "src/pluginmeta.js~pluginmetalist#constructor",
    "class/src/pluginmeta.js~PluginMetaList.html#instance-constructor-constructor",
    "src/pluginmeta.js~PluginMetaList#constructor",
    "method"
  ],
  [
    "src/pluginmeta.js~pluginmetalist#getfeeds",
    "class/src/pluginmeta.js~PluginMetaList.html#instance-method-getFeeds",
    "src/pluginmeta.js~PluginMetaList#getFeeds",
    "method"
  ],
  [
    "src/pluginmeta.js~pluginmetalist#getplugins",
    "class/src/pluginmeta.js~PluginMetaList.html#instance-method-getPlugins",
    "src/pluginmeta.js~PluginMetaList#getPlugins",
    "method"
  ],
  [
    "src/pluginmeta.js~pluginmetalist#itemclass",
    "class/src/pluginmeta.js~PluginMetaList.html#instance-member-itemClass",
    "src/pluginmeta.js~PluginMetaList#itemClass",
    "member"
  ],
  [
    "src/pluginparameter.js",
    "file/src/pluginparameter.js.html",
    "src/pluginparameter.js",
    "file"
  ],
  [
    "src/pluginparameter.js~pluginparameter#getplugin",
    "class/src/pluginparameter.js~PluginParameter.html#instance-method-getPlugin",
    "src/pluginparameter.js~PluginParameter#getPlugin",
    "method"
  ],
  [
    "src/pluginparameter.js~pluginparameterlist#constructor",
    "class/src/pluginparameter.js~PluginParameterList.html#instance-constructor-constructor",
    "src/pluginparameter.js~PluginParameterList#constructor",
    "method"
  ],
  [
    "src/pluginparameter.js~pluginparameterlist#getplugin",
    "class/src/pluginparameter.js~PluginParameterList.html#instance-method-getPlugin",
    "src/pluginparameter.js~PluginParameterList#getPlugin",
    "method"
  ],
  [
    "src/pluginparameter.js~pluginparameterlist#itemclass",
    "class/src/pluginparameter.js~PluginParameterList.html#instance-member-itemClass",
    "src/pluginparameter.js~PluginParameterList#itemClass",
    "member"
  ],
  [
    "src/request.js",
    "file/src/request.js.html",
    "src/request.js",
    "file"
  ],
  [
    "src/request.js~request#_getconfig",
    "class/src/request.js~Request.html#instance-method-_getConfig",
    "src/request.js~Request#_getConfig",
    "method"
  ],
  [
    "src/request.js~request#_postorput",
    "class/src/request.js~Request.html#instance-method-_postOrPut",
    "src/request.js~Request#_postOrPut",
    "method"
  ],
  [
    "src/request.js~request#auth",
    "class/src/request.js~Request.html#instance-member-auth",
    "src/request.js~Request#auth",
    "member"
  ],
  [
    "src/request.js~request#constructor",
    "class/src/request.js~Request.html#instance-constructor-constructor",
    "src/request.js~Request#constructor",
    "method"
  ],
  [
    "src/request.js~request#contenttype",
    "class/src/request.js~Request.html#instance-member-contentType",
    "src/request.js~Request#contentType",
    "member"
  ],
  [
    "src/request.js~request#delete",
    "class/src/request.js~Request.html#instance-method-delete",
    "src/request.js~Request#delete",
    "method"
  ],
  [
    "src/request.js~request#get",
    "class/src/request.js~Request.html#instance-method-get",
    "src/request.js~Request#get",
    "method"
  ],
  [
    "src/request.js~request#post",
    "class/src/request.js~Request.html#instance-method-post",
    "src/request.js~Request#post",
    "method"
  ],
  [
    "src/request.js~request#put",
    "class/src/request.js~Request.html#instance-method-put",
    "src/request.js~Request#put",
    "method"
  ],
  [
    "src/request.js~request#timeout",
    "class/src/request.js~Request.html#instance-member-timeout",
    "src/request.js~Request#timeout",
    "member"
  ],
  [
    "src/request.js~request._callaxios",
    "class/src/request.js~Request.html#static-method-_callAxios",
    "src/request.js~Request._callAxios",
    "method"
  ],
  [
    "src/request.js~request._handlerequesterror",
    "class/src/request.js~Request.html#static-method-_handleRequestError",
    "src/request.js~Request._handleRequestError",
    "method"
  ],
  [
    "src/request.js~request.runasynctask",
    "class/src/request.js~Request.html#static-method-runAsyncTask",
    "src/request.js~Request.runAsyncTask",
    "method"
  ],
  [
    "src/resource.js",
    "file/src/resource.js.html",
    "src/resource.js",
    "file"
  ],
  [
    "src/resource.js~itemresource#_delete",
    "class/src/resource.js~ItemResource.html#instance-method-_delete",
    "src/resource.js~ItemResource#_delete",
    "method"
  ],
  [
    "src/resource.js~itemresource#_getresource",
    "class/src/resource.js~ItemResource.html#instance-method-_getResource",
    "src/resource.js~ItemResource#_getResource",
    "method"
  ],
  [
    "src/resource.js~itemresource#_put",
    "class/src/resource.js~ItemResource.html#instance-method-_put",
    "src/resource.js~ItemResource#_put",
    "method"
  ],
  [
    "src/resource.js~itemresource#collection",
    "class/src/resource.js~ItemResource.html#instance-member-collection",
    "src/resource.js~ItemResource#collection",
    "member"
  ],
  [
    "src/resource.js~itemresource#constructor",
    "class/src/resource.js~ItemResource.html#instance-constructor-constructor",
    "src/resource.js~ItemResource#constructor",
    "method"
  ],
  [
    "src/resource.js~itemresource#data",
    "class/src/resource.js~ItemResource.html#instance-get-data",
    "src/resource.js~ItemResource#data",
    "member"
  ],
  [
    "src/resource.js~itemresource#get",
    "class/src/resource.js~ItemResource.html#instance-method-get",
    "src/resource.js~ItemResource#get",
    "method"
  ],
  [
    "src/resource.js~itemresource#getputparameters",
    "class/src/resource.js~ItemResource.html#instance-method-getPUTParameters",
    "src/resource.js~ItemResource#getPUTParameters",
    "method"
  ],
  [
    "src/resource.js~listresource#_getresource",
    "class/src/resource.js~ListResource.html#instance-method-_getResource",
    "src/resource.js~ListResource#_getResource",
    "method"
  ],
  [
    "src/resource.js~listresource#_post",
    "class/src/resource.js~ListResource.html#instance-method-_post",
    "src/resource.js~ListResource#_post",
    "method"
  ],
  [
    "src/resource.js~listresource#collection",
    "class/src/resource.js~ListResource.html#instance-member-collection",
    "src/resource.js~ListResource#collection",
    "member"
  ],
  [
    "src/resource.js~listresource#constructor",
    "class/src/resource.js~ListResource.html#instance-constructor-constructor",
    "src/resource.js~ListResource#constructor",
    "method"
  ],
  [
    "src/resource.js~listresource#data",
    "class/src/resource.js~ListResource.html#instance-get-data",
    "src/resource.js~ListResource#data",
    "member"
  ],
  [
    "src/resource.js~listresource#get",
    "class/src/resource.js~ListResource.html#instance-method-get",
    "src/resource.js~ListResource#get",
    "method"
  ],
  [
    "src/resource.js~listresource#getitem",
    "class/src/resource.js~ListResource.html#instance-method-getItem",
    "src/resource.js~ListResource#getItem",
    "method"
  ],
  [
    "src/resource.js~listresource#getitems",
    "class/src/resource.js~ListResource.html#instance-method-getItems",
    "src/resource.js~ListResource#getItems",
    "method"
  ],
  [
    "src/resource.js~listresource#getpostparameters",
    "class/src/resource.js~ListResource.html#instance-method-getPOSTParameters",
    "src/resource.js~ListResource#getPOSTParameters",
    "method"
  ],
  [
    "src/resource.js~listresource#getsearchparameters",
    "class/src/resource.js~ListResource.html#instance-method-getSearchParameters",
    "src/resource.js~ListResource#getSearchParameters",
    "method"
  ],
  [
    "src/resource.js~listresource#hasnextpage",
    "class/src/resource.js~ListResource.html#instance-get-hasNextPage",
    "src/resource.js~ListResource#hasNextPage",
    "member"
  ],
  [
    "src/resource.js~listresource#haspreviouspage",
    "class/src/resource.js~ListResource.html#instance-get-hasPreviousPage",
    "src/resource.js~ListResource#hasPreviousPage",
    "member"
  ],
  [
    "src/resource.js~listresource#itemclass",
    "class/src/resource.js~ListResource.html#instance-member-itemClass",
    "src/resource.js~ListResource#itemClass",
    "member"
  ],
  [
    "src/resource.js~listresource#queryurl",
    "class/src/resource.js~ListResource.html#instance-member-queryUrl",
    "src/resource.js~ListResource#queryUrl",
    "member"
  ],
  [
    "src/resource.js~listresource#searchparams",
    "class/src/resource.js~ListResource.html#instance-member-searchParams",
    "src/resource.js~ListResource#searchParams",
    "member"
  ],
  [
    "src/resource.js~listresource#totalcount",
    "class/src/resource.js~ListResource.html#instance-get-totalCount",
    "src/resource.js~ListResource#totalCount",
    "member"
  ],
  [
    "src/resource.js~resource#auth",
    "class/src/resource.js~Resource.html#instance-member-auth",
    "src/resource.js~Resource#auth",
    "member"
  ],
  [
    "src/resource.js~resource#clone",
    "class/src/resource.js~Resource.html#instance-method-clone",
    "src/resource.js~Resource#clone",
    "method"
  ],
  [
    "src/resource.js~resource#collection",
    "class/src/resource.js~Resource.html#instance-member-collection",
    "src/resource.js~Resource#collection",
    "member"
  ],
  [
    "src/resource.js~resource#constructor",
    "class/src/resource.js~Resource.html#instance-constructor-constructor",
    "src/resource.js~Resource#constructor",
    "method"
  ],
  [
    "src/resource.js~resource#contenttype",
    "class/src/resource.js~Resource.html#instance-member-contentType",
    "src/resource.js~Resource#contentType",
    "member"
  ],
  [
    "src/resource.js~resource#isempty",
    "class/src/resource.js~Resource.html#instance-get-isEmpty",
    "src/resource.js~Resource#isEmpty",
    "member"
  ],
  [
    "src/resource.js~resource#url",
    "class/src/resource.js~Resource.html#instance-member-url",
    "src/resource.js~Resource#url",
    "member"
  ],
  [
    "src/resource.js~resource.cloneobj",
    "class/src/resource.js~Resource.html#static-method-cloneObj",
    "src/resource.js~Resource.cloneObj",
    "method"
  ],
  [
    "src/servicefile.js",
    "file/src/servicefile.js.html",
    "src/servicefile.js",
    "file"
  ],
  [
    "src/servicefile.js~servicefile#constructor",
    "class/src/servicefile.js~ServiceFile.html#instance-constructor-constructor",
    "src/servicefile.js~ServiceFile#constructor",
    "method"
  ],
  [
    "src/servicefile.js~servicefile#getfileblob",
    "class/src/servicefile.js~ServiceFile.html#instance-method-getFileBlob",
    "src/servicefile.js~ServiceFile#getFileBlob",
    "method"
  ],
  [
    "src/servicefile.js~servicefile#getparentfolder",
    "class/src/servicefile.js~ServiceFile.html#instance-method-getParentFolder",
    "src/servicefile.js~ServiceFile#getParentFolder",
    "method"
  ],
  [
    "src/servicefile.js~servicefilelist#constructor",
    "class/src/servicefile.js~ServiceFileList.html#instance-constructor-constructor",
    "src/servicefile.js~ServiceFileList#constructor",
    "method"
  ],
  [
    "src/servicefile.js~servicefilelist#itemclass",
    "class/src/servicefile.js~ServiceFileList.html#instance-member-itemClass",
    "src/servicefile.js~ServiceFileList#itemClass",
    "member"
  ],
  [
    "src/tag.js",
    "file/src/tag.js.html",
    "src/tag.js",
    "file"
  ],
  [
    "src/tag.js~feedtaglist#constructor",
    "class/src/tag.js~FeedTagList.html#instance-constructor-constructor",
    "src/tag.js~FeedTagList#constructor",
    "method"
  ],
  [
    "src/tag.js~feedtaglist#getfeed",
    "class/src/tag.js~FeedTagList.html#instance-method-getFeed",
    "src/tag.js~FeedTagList#getFeed",
    "method"
  ],
  [
    "src/tag.js~feedtaglist#itemclass",
    "class/src/tag.js~FeedTagList.html#instance-member-itemClass",
    "src/tag.js~FeedTagList#itemClass",
    "member"
  ],
  [
    "src/tag.js~feedtagginglist#constructor",
    "class/src/tag.js~FeedTaggingList.html#instance-constructor-constructor",
    "src/tag.js~FeedTaggingList#constructor",
    "method"
  ],
  [
    "src/tag.js~feedtagginglist#getfeed",
    "class/src/tag.js~FeedTaggingList.html#instance-method-getFeed",
    "src/tag.js~FeedTaggingList#getFeed",
    "method"
  ],
  [
    "src/tag.js~feedtagginglist#itemclass",
    "class/src/tag.js~FeedTaggingList.html#instance-member-itemClass",
    "src/tag.js~FeedTaggingList#itemClass",
    "member"
  ],
  [
    "src/tag.js~feedtagginglist#post",
    "class/src/tag.js~FeedTaggingList.html#instance-method-post",
    "src/tag.js~FeedTaggingList#post",
    "method"
  ],
  [
    "src/tag.js~tag#constructor",
    "class/src/tag.js~Tag.html#instance-constructor-constructor",
    "src/tag.js~Tag#constructor",
    "method"
  ],
  [
    "src/tag.js~tag#delete",
    "class/src/tag.js~Tag.html#instance-method-delete",
    "src/tag.js~Tag#delete",
    "method"
  ],
  [
    "src/tag.js~tag#gettaggedfeeds",
    "class/src/tag.js~Tag.html#instance-method-getTaggedFeeds",
    "src/tag.js~Tag#getTaggedFeeds",
    "method"
  ],
  [
    "src/tag.js~tag#gettaggings",
    "class/src/tag.js~Tag.html#instance-method-getTaggings",
    "src/tag.js~Tag#getTaggings",
    "method"
  ],
  [
    "src/tag.js~tag#put",
    "class/src/tag.js~Tag.html#instance-method-put",
    "src/tag.js~Tag#put",
    "method"
  ],
  [
    "src/tag.js~tagfeedlist#constructor",
    "class/src/tag.js~TagFeedList.html#instance-constructor-constructor",
    "src/tag.js~TagFeedList#constructor",
    "method"
  ],
  [
    "src/tag.js~tagfeedlist#gettag",
    "class/src/tag.js~TagFeedList.html#instance-method-getTag",
    "src/tag.js~TagFeedList#getTag",
    "method"
  ],
  [
    "src/tag.js~tagfeedlist#itemclass",
    "class/src/tag.js~TagFeedList.html#instance-member-itemClass",
    "src/tag.js~TagFeedList#itemClass",
    "member"
  ],
  [
    "src/tag.js~taglist#constructor",
    "class/src/tag.js~TagList.html#instance-constructor-constructor",
    "src/tag.js~TagList#constructor",
    "method"
  ],
  [
    "src/tag.js~taglist#getfeeds",
    "class/src/tag.js~TagList.html#instance-method-getFeeds",
    "src/tag.js~TagList#getFeeds",
    "method"
  ],
  [
    "src/tag.js~taglist#itemclass",
    "class/src/tag.js~TagList.html#instance-member-itemClass",
    "src/tag.js~TagList#itemClass",
    "member"
  ],
  [
    "src/tag.js~taglist#post",
    "class/src/tag.js~TagList.html#instance-method-post",
    "src/tag.js~TagList#post",
    "method"
  ],
  [
    "src/tag.js~tagtagginglist#constructor",
    "class/src/tag.js~TagTaggingList.html#instance-constructor-constructor",
    "src/tag.js~TagTaggingList#constructor",
    "method"
  ],
  [
    "src/tag.js~tagtagginglist#gettag",
    "class/src/tag.js~TagTaggingList.html#instance-method-getTag",
    "src/tag.js~TagTaggingList#getTag",
    "method"
  ],
  [
    "src/tag.js~tagtagginglist#itemclass",
    "class/src/tag.js~TagTaggingList.html#instance-member-itemClass",
    "src/tag.js~TagTaggingList#itemClass",
    "member"
  ],
  [
    "src/tag.js~tagtagginglist#post",
    "class/src/tag.js~TagTaggingList.html#instance-method-post",
    "src/tag.js~TagTaggingList#post",
    "method"
  ],
  [
    "src/tag.js~tagging#constructor",
    "class/src/tag.js~Tagging.html#instance-constructor-constructor",
    "src/tag.js~Tagging#constructor",
    "method"
  ],
  [
    "src/tag.js~tagging#delete",
    "class/src/tag.js~Tagging.html#instance-method-delete",
    "src/tag.js~Tagging#delete",
    "method"
  ],
  [
    "src/tag.js~tagging#getfeed",
    "class/src/tag.js~Tagging.html#instance-method-getFeed",
    "src/tag.js~Tagging#getFeed",
    "method"
  ],
  [
    "src/tag.js~tagging#gettag",
    "class/src/tag.js~Tagging.html#instance-method-getTag",
    "src/tag.js~Tagging#getTag",
    "method"
  ],
  [
    "src/user.js",
    "file/src/user.js.html",
    "src/user.js",
    "file"
  ],
  [
    "src/user.js~user#constructor",
    "class/src/user.js~User.html#instance-constructor-constructor",
    "src/user.js~User#constructor",
    "method"
  ],
  [
    "src/user.js~user#put",
    "class/src/user.js~User.html#instance-method-put",
    "src/user.js~User#put",
    "method"
  ],
  [
    "src/userfile.js",
    "file/src/userfile.js.html",
    "src/userfile.js",
    "file"
  ],
  [
    "src/userfile.js~userfile#delete",
    "class/src/userfile.js~UserFile.html#instance-method-delete",
    "src/userfile.js~UserFile#delete",
    "method"
  ],
  [
    "src/userfile.js~userfile#getfileblob",
    "class/src/userfile.js~UserFile.html#instance-method-getFileBlob",
    "src/userfile.js~UserFile#getFileBlob",
    "method"
  ],
  [
    "src/userfile.js~userfile#getparentfolder",
    "class/src/userfile.js~UserFile.html#instance-method-getParentFolder",
    "src/userfile.js~UserFile#getParentFolder",
    "method"
  ],
  [
    "src/userfile.js~userfile#put",
    "class/src/userfile.js~UserFile.html#instance-method-put",
    "src/userfile.js~UserFile#put",
    "method"
  ],
  [
    "src/userfile.js~userfilelist#constructor",
    "class/src/userfile.js~UserFileList.html#instance-constructor-constructor",
    "src/userfile.js~UserFileList#constructor",
    "method"
  ],
  [
    "src/userfile.js~userfilelist#itemclass",
    "class/src/userfile.js~UserFileList.html#instance-member-itemClass",
    "src/userfile.js~UserFileList#itemClass",
    "member"
  ],
  [
    "src/userfile.js~userfilelist#post",
    "class/src/userfile.js~UserFileList.html#instance-method-post",
    "src/userfile.js~UserFileList#post",
    "method"
  ],
  [
    "src/workflow.js",
    "file/src/workflow.js.html",
    "src/workflow.js",
    "file"
  ],
  [
    "src/workflow.js~allworkflowlist#constructor",
    "class/src/workflow.js~AllWorkflowList.html#instance-constructor-constructor",
    "src/workflow.js~AllWorkflowList#constructor",
    "method"
  ],
  [
    "src/workflow.js~allworkflowlist#getpipelines",
    "class/src/workflow.js~AllWorkflowList.html#instance-method-getPipelines",
    "src/workflow.js~AllWorkflowList#getPipelines",
    "method"
  ],
  [
    "src/workflow.js~allworkflowlist#itemclass",
    "class/src/workflow.js~AllWorkflowList.html#instance-member-itemClass",
    "src/workflow.js~AllWorkflowList#itemClass",
    "member"
  ],
  [
    "src/workflow.js~workflow#constructor",
    "class/src/workflow.js~Workflow.html#instance-constructor-constructor",
    "src/workflow.js~Workflow#constructor",
    "method"
  ],
  [
    "src/workflow.js~workflow#delete",
    "class/src/workflow.js~Workflow.html#instance-method-delete",
    "src/workflow.js~Workflow#delete",
    "method"
  ],
  [
    "src/workflow.js~workflow#getpipeline",
    "class/src/workflow.js~Workflow.html#instance-method-getPipeline",
    "src/workflow.js~Workflow#getPipeline",
    "method"
  ],
  [
    "src/workflow.js~workflow#getplugininstances",
    "class/src/workflow.js~Workflow.html#instance-method-getPluginInstances",
    "src/workflow.js~Workflow#getPluginInstances",
    "method"
  ],
  [
    "src/workflow.js~workflow#put",
    "class/src/workflow.js~Workflow.html#instance-method-put",
    "src/workflow.js~Workflow#put",
    "method"
  ],
  [
    "src/workflow.js~workflowlist#constructor",
    "class/src/workflow.js~WorkflowList.html#instance-constructor-constructor",
    "src/workflow.js~WorkflowList#constructor",
    "method"
  ],
  [
    "src/workflow.js~workflowlist#getpipeline",
    "class/src/workflow.js~WorkflowList.html#instance-method-getPipeline",
    "src/workflow.js~WorkflowList#getPipeline",
    "method"
  ],
  [
    "src/workflow.js~workflowlist#itemclass",
    "class/src/workflow.js~WorkflowList.html#instance-member-itemClass",
    "src/workflow.js~WorkflowList#itemClass",
    "member"
  ],
  [
    "src/workflow.js~workflowlist#post",
    "class/src/workflow.js~WorkflowList.html#instance-method-post",
    "src/workflow.js~WorkflowList#post",
    "method"
  ]
]