window.esdocSearchIndex = [
  [
    "@fnndsc/chrisapi~client",
    "class/src/client.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~collection",
    "class/src/cj.js~Collection.html",
    "<span>Collection</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~comment",
    "class/src/comment.js~Comment.html",
    "<span>Comment</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~commentlist",
    "class/src/comment.js~CommentList.html",
    "<span>CommentList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feed",
    "class/src/feed.js~Feed.html",
    "<span>Feed</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedfile",
    "class/src/feedfile.js~FeedFile.html",
    "<span>FeedFile</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedfilelist",
    "class/src/feedfile.js~FeedFileList.html",
    "<span>FeedFileList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedlist",
    "class/src/feed.js~FeedList.html",
    "<span>FeedList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedplugininstancelist",
    "class/src/plugininstance.js~FeedPluginInstanceList.html",
    "<span>FeedPluginInstanceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedtaglist",
    "class/src/tag.js~FeedTagList.html",
    "<span>FeedTagList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~feedtagginglist",
    "class/src/tag.js~FeedTaggingList.html",
    "<span>FeedTaggingList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~itemresource",
    "class/src/resource.js~ItemResource.html",
    "<span>ItemResource</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~listresource",
    "class/src/resource.js~ListResource.html",
    "<span>ListResource</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~note",
    "class/src/note.js~Note.html",
    "<span>Note</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugin",
    "class/src/plugin.js~Plugin.html",
    "<span>Plugin</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstance",
    "class/src/plugininstance.js~PluginInstance.html",
    "<span>PluginInstance</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstancedescendantlist",
    "class/src/plugininstance.js~PluginInstanceDescendantList.html",
    "<span>PluginInstanceDescendantList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstancefilelist",
    "class/src/feedfile.js~PluginInstanceFileList.html",
    "<span>PluginInstanceFileList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstancelist",
    "class/src/plugininstance.js~PluginInstanceList.html",
    "<span>PluginInstanceList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstanceparameter",
    "class/src/plugininstance.js~PluginInstanceParameter.html",
    "<span>PluginInstanceParameter</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~plugininstanceparameterlist",
    "class/src/plugininstance.js~PluginInstanceParameterList.html",
    "<span>PluginInstanceParameterList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginlist",
    "class/src/plugin.js~PluginList.html",
    "<span>PluginList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginparameter",
    "class/src/pluginparameter.js~PluginParameter.html",
    "<span>PluginParameter</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~pluginparameterlist",
    "class/src/pluginparameter.js~PluginParameterList.html",
    "<span>PluginParameterList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~request",
    "class/src/request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~requestexception",
    "class/src/exception.js~RequestException.html",
    "<span>RequestException</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~resource",
    "class/src/resource.js~Resource.html",
    "<span>Resource</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~tag",
    "class/src/tag.js~Tag.html",
    "<span>Tag</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~tagfeedlist",
    "class/src/tag.js~TagFeedList.html",
    "<span>TagFeedList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~taglist",
    "class/src/tag.js~TagList.html",
    "<span>TagList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~tagtagginglist",
    "class/src/tag.js~TagTaggingList.html",
    "<span>TagTaggingList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~tagging",
    "class/src/tag.js~Tagging.html",
    "<span>Tagging</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~uploadedfile",
    "class/src/uploadedfile.js~UploadedFile.html",
    "<span>UploadedFile</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~uploadedfilelist",
    "class/src/uploadedfile.js~UploadedFileList.html",
    "<span>UploadedFileList</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisapi~user",
    "class/src/user.js~User.html",
    "<span>User</span> <span class=\"search-result-import-path\">@fnndsc/chrisapi</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/cj.js",
    "file/src/cj.js.html",
    "src/cj.js",
    "file"
  ],
  [
    "src/cj.js~collection.geterrormessage",
    "class/src/cj.js~Collection.html#static-method-getErrorMessage",
    "src/cj.js~Collection.getErrorMessage",
    "method"
  ],
  [
    "src/cj.js~collection.getitemdescriptors",
    "class/src/cj.js~Collection.html#static-method-getItemDescriptors",
    "src/cj.js~Collection.getItemDescriptors",
    "method"
  ],
  [
    "src/cj.js~collection.getlinkrelationurls",
    "class/src/cj.js~Collection.html#static-method-getLinkRelationUrls",
    "src/cj.js~Collection.getLinkRelationUrls",
    "method"
  ],
  [
    "src/cj.js~collection.getqueryparameters",
    "class/src/cj.js~Collection.html#static-method-getQueryParameters",
    "src/cj.js~Collection.getQueryParameters",
    "method"
  ],
  [
    "src/cj.js~collection.gettemplatedescriptornames",
    "class/src/cj.js~Collection.html#static-method-getTemplateDescriptorNames",
    "src/cj.js~Collection.getTemplateDescriptorNames",
    "method"
  ],
  [
    "src/cj.js~collection.geturl",
    "class/src/cj.js~Collection.html#static-method-getUrl",
    "src/cj.js~Collection.getUrl",
    "method"
  ],
  [
    "src/cj.js~collection.maketemplate",
    "class/src/cj.js~Collection.html#static-method-makeTemplate",
    "src/cj.js~Collection.makeTemplate",
    "method"
  ],
  [
    "src/client.js",
    "file/src/client.js.html",
    "src/client.js",
    "file"
  ],
  [
    "src/client.js~client#auth",
    "class/src/client.js~Client.html#instance-member-auth",
    "src/client.js~Client#auth",
    "member"
  ],
  [
    "src/client.js~client#constructor",
    "class/src/client.js~Client.html#instance-constructor-constructor",
    "src/client.js~Client#constructor",
    "method"
  ],
  [
    "src/client.js~client#getfeeds",
    "class/src/client.js~Client.html#instance-method-getFeeds",
    "src/client.js~Client#getFeeds",
    "method"
  ],
  [
    "src/client.js~client#url",
    "class/src/client.js~Client.html#instance-member-url",
    "src/client.js~Client#url",
    "member"
  ],
  [
    "src/client.js~client.createuser",
    "class/src/client.js~Client.html#static-method-createUser",
    "src/client.js~Client.createUser",
    "method"
  ],
  [
    "src/client.js~client.getauthtoken",
    "class/src/client.js~Client.html#static-method-getAuthToken",
    "src/client.js~Client.getAuthToken",
    "method"
  ],
  [
    "src/client.js~client.runasynctask",
    "class/src/client.js~Client.html#static-method-runAsyncTask",
    "src/client.js~Client.runAsyncTask",
    "method"
  ],
  [
    "src/comment.js",
    "file/src/comment.js.html",
    "src/comment.js",
    "file"
  ],
  [
    "src/comment.js~comment#constructor",
    "class/src/comment.js~Comment.html#instance-constructor-constructor",
    "src/comment.js~Comment#constructor",
    "method"
  ],
  [
    "src/comment.js~comment#delete",
    "class/src/comment.js~Comment.html#instance-method-delete",
    "src/comment.js~Comment#delete",
    "method"
  ],
  [
    "src/comment.js~comment#getfeed",
    "class/src/comment.js~Comment.html#instance-method-getFeed",
    "src/comment.js~Comment#getFeed",
    "method"
  ],
  [
    "src/comment.js~comment#put",
    "class/src/comment.js~Comment.html#instance-method-put",
    "src/comment.js~Comment#put",
    "method"
  ],
  [
    "src/comment.js~commentlist#constructor",
    "class/src/comment.js~CommentList.html#instance-constructor-constructor",
    "src/comment.js~CommentList#constructor",
    "method"
  ],
  [
    "src/comment.js~commentlist#getfeed",
    "class/src/comment.js~CommentList.html#instance-method-getFeed",
    "src/comment.js~CommentList#getFeed",
    "method"
  ],
  [
    "src/comment.js~commentlist#itemclass",
    "class/src/comment.js~CommentList.html#instance-member-itemClass",
    "src/comment.js~CommentList#itemClass",
    "member"
  ],
  [
    "src/comment.js~commentlist#post",
    "class/src/comment.js~CommentList.html#instance-method-post",
    "src/comment.js~CommentList#post",
    "method"
  ],
  [
    "src/exception.js",
    "file/src/exception.js.html",
    "src/exception.js",
    "file"
  ],
  [
    "src/exception.js~requestexception#constructor",
    "class/src/exception.js~RequestException.html#instance-constructor-constructor",
    "src/exception.js~RequestException#constructor",
    "method"
  ],
  [
    "src/exception.js~requestexception#name",
    "class/src/exception.js~RequestException.html#instance-member-name",
    "src/exception.js~RequestException#name",
    "member"
  ],
  [
    "src/feed.js",
    "file/src/feed.js.html",
    "src/feed.js",
    "file"
  ],
  [
    "src/feed.js~feed#constructor",
    "class/src/feed.js~Feed.html#instance-constructor-constructor",
    "src/feed.js~Feed#constructor",
    "method"
  ],
  [
    "src/feed.js~feed#delete",
    "class/src/feed.js~Feed.html#instance-method-delete",
    "src/feed.js~Feed#delete",
    "method"
  ],
  [
    "src/feed.js~feed#getcomments",
    "class/src/feed.js~Feed.html#instance-method-getComments",
    "src/feed.js~Feed#getComments",
    "method"
  ],
  [
    "src/feed.js~feed#getfiles",
    "class/src/feed.js~Feed.html#instance-method-getFiles",
    "src/feed.js~Feed#getFiles",
    "method"
  ],
  [
    "src/feed.js~feed#getnote",
    "class/src/feed.js~Feed.html#instance-method-getNote",
    "src/feed.js~Feed#getNote",
    "method"
  ],
  [
    "src/feed.js~feed#getplugininstances",
    "class/src/feed.js~Feed.html#instance-method-getPluginInstances",
    "src/feed.js~Feed#getPluginInstances",
    "method"
  ],
  [
    "src/feed.js~feed#gettaggings",
    "class/src/feed.js~Feed.html#instance-method-getTaggings",
    "src/feed.js~Feed#getTaggings",
    "method"
  ],
  [
    "src/feed.js~feed#gettags",
    "class/src/feed.js~Feed.html#instance-method-getTags",
    "src/feed.js~Feed#getTags",
    "method"
  ],
  [
    "src/feed.js~feed#put",
    "class/src/feed.js~Feed.html#instance-method-put",
    "src/feed.js~Feed#put",
    "method"
  ],
  [
    "src/feed.js~feedlist#constructor",
    "class/src/feed.js~FeedList.html#instance-constructor-constructor",
    "src/feed.js~FeedList#constructor",
    "method"
  ],
  [
    "src/feed.js~feedlist#getplugins",
    "class/src/feed.js~FeedList.html#instance-method-getPlugins",
    "src/feed.js~FeedList#getPlugins",
    "method"
  ],
  [
    "src/feed.js~feedlist#gettags",
    "class/src/feed.js~FeedList.html#instance-method-getTags",
    "src/feed.js~FeedList#getTags",
    "method"
  ],
  [
    "src/feed.js~feedlist#getuploadedfiles",
    "class/src/feed.js~FeedList.html#instance-method-getUploadedFiles",
    "src/feed.js~FeedList#getUploadedFiles",
    "method"
  ],
  [
    "src/feed.js~feedlist#getuser",
    "class/src/feed.js~FeedList.html#instance-method-getUser",
    "src/feed.js~FeedList#getUser",
    "method"
  ],
  [
    "src/feed.js~feedlist#itemclass",
    "class/src/feed.js~FeedList.html#instance-member-itemClass",
    "src/feed.js~FeedList#itemClass",
    "member"
  ],
  [
    "src/feedfile.js",
    "file/src/feedfile.js.html",
    "src/feedfile.js",
    "file"
  ],
  [
    "src/feedfile.js~feedfile#constructor",
    "class/src/feedfile.js~FeedFile.html#instance-constructor-constructor",
    "src/feedfile.js~FeedFile#constructor",
    "method"
  ],
  [
    "src/feedfile.js~feedfile#getfileblob",
    "class/src/feedfile.js~FeedFile.html#instance-method-getFileBlob",
    "src/feedfile.js~FeedFile#getFileBlob",
    "method"
  ],
  [
    "src/feedfile.js~feedfile#getplugininstance",
    "class/src/feedfile.js~FeedFile.html#instance-method-getPluginInstance",
    "src/feedfile.js~FeedFile#getPluginInstance",
    "method"
  ],
  [
    "src/feedfile.js~feedfilelist#constructor",
    "class/src/feedfile.js~FeedFileList.html#instance-constructor-constructor",
    "src/feedfile.js~FeedFileList#constructor",
    "method"
  ],
  [
    "src/feedfile.js~feedfilelist#getfeed",
    "class/src/feedfile.js~FeedFileList.html#instance-method-getFeed",
    "src/feedfile.js~FeedFileList#getFeed",
    "method"
  ],
  [
    "src/feedfile.js~feedfilelist#itemclass",
    "class/src/feedfile.js~FeedFileList.html#instance-member-itemClass",
    "src/feedfile.js~FeedFileList#itemClass",
    "member"
  ],
  [
    "src/feedfile.js~plugininstancefilelist#constructor",
    "class/src/feedfile.js~PluginInstanceFileList.html#instance-constructor-constructor",
    "src/feedfile.js~PluginInstanceFileList#constructor",
    "method"
  ],
  [
    "src/feedfile.js~plugininstancefilelist#getfeed",
    "class/src/feedfile.js~PluginInstanceFileList.html#instance-method-getFeed",
    "src/feedfile.js~PluginInstanceFileList#getFeed",
    "method"
  ],
  [
    "src/feedfile.js~plugininstancefilelist#getplugininstance",
    "class/src/feedfile.js~PluginInstanceFileList.html#instance-method-getPluginInstance",
    "src/feedfile.js~PluginInstanceFileList#getPluginInstance",
    "method"
  ],
  [
    "src/feedfile.js~plugininstancefilelist#itemclass",
    "class/src/feedfile.js~PluginInstanceFileList.html#instance-member-itemClass",
    "src/feedfile.js~PluginInstanceFileList#itemClass",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/note.js",
    "file/src/note.js.html",
    "src/note.js",
    "file"
  ],
  [
    "src/note.js~note#constructor",
    "class/src/note.js~Note.html#instance-constructor-constructor",
    "src/note.js~Note#constructor",
    "method"
  ],
  [
    "src/note.js~note#put",
    "class/src/note.js~Note.html#instance-method-put",
    "src/note.js~Note#put",
    "method"
  ],
  [
    "src/plugin.js",
    "file/src/plugin.js.html",
    "src/plugin.js",
    "file"
  ],
  [
    "src/plugin.js~plugin#constructor",
    "class/src/plugin.js~Plugin.html#instance-constructor-constructor",
    "src/plugin.js~Plugin#constructor",
    "method"
  ],
  [
    "src/plugin.js~plugin#getplugininstances",
    "class/src/plugin.js~Plugin.html#instance-method-getPluginInstances",
    "src/plugin.js~Plugin#getPluginInstances",
    "method"
  ],
  [
    "src/plugin.js~plugin#getpluginparameters",
    "class/src/plugin.js~Plugin.html#instance-method-getPluginParameters",
    "src/plugin.js~Plugin#getPluginParameters",
    "method"
  ],
  [
    "src/plugin.js~pluginlist#constructor",
    "class/src/plugin.js~PluginList.html#instance-constructor-constructor",
    "src/plugin.js~PluginList#constructor",
    "method"
  ],
  [
    "src/plugin.js~pluginlist#getfeeds",
    "class/src/plugin.js~PluginList.html#instance-method-getFeeds",
    "src/plugin.js~PluginList#getFeeds",
    "method"
  ],
  [
    "src/plugin.js~pluginlist#itemclass",
    "class/src/plugin.js~PluginList.html#instance-member-itemClass",
    "src/plugin.js~PluginList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js",
    "file/src/plugininstance.js.html",
    "src/plugininstance.js",
    "file"
  ],
  [
    "src/plugininstance.js~feedplugininstancelist#constructor",
    "class/src/plugininstance.js~FeedPluginInstanceList.html#instance-constructor-constructor",
    "src/plugininstance.js~FeedPluginInstanceList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~feedplugininstancelist#getfeed",
    "class/src/plugininstance.js~FeedPluginInstanceList.html#instance-method-getFeed",
    "src/plugininstance.js~FeedPluginInstanceList#getFeed",
    "method"
  ],
  [
    "src/plugininstance.js~feedplugininstancelist#itemclass",
    "class/src/plugininstance.js~FeedPluginInstanceList.html#instance-member-itemClass",
    "src/plugininstance.js~FeedPluginInstanceList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~plugininstance#constructor",
    "class/src/plugininstance.js~PluginInstance.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstance#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getdescendantplugininstances",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getDescendantPluginInstances",
    "src/plugininstance.js~PluginInstance#getDescendantPluginInstances",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getfeed",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getFeed",
    "src/plugininstance.js~PluginInstance#getFeed",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getfiles",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getFiles",
    "src/plugininstance.js~PluginInstance#getFiles",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getparameters",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getParameters",
    "src/plugininstance.js~PluginInstance#getParameters",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getplugin",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getPlugin",
    "src/plugininstance.js~PluginInstance#getPlugin",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstance#getpreviousplugininstance",
    "class/src/plugininstance.js~PluginInstance.html#instance-method-getPreviousPluginInstance",
    "src/plugininstance.js~PluginInstance#getPreviousPluginInstance",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancedescendantlist#constructor",
    "class/src/plugininstance.js~PluginInstanceDescendantList.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstanceDescendantList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancedescendantlist#itemclass",
    "class/src/plugininstance.js~PluginInstanceDescendantList.html#instance-member-itemClass",
    "src/plugininstance.js~PluginInstanceDescendantList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~plugininstancelist#constructor",
    "class/src/plugininstance.js~PluginInstanceList.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstanceList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancelist#getplugin",
    "class/src/plugininstance.js~PluginInstanceList.html#instance-method-getPlugin",
    "src/plugininstance.js~PluginInstanceList#getPlugin",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstancelist#itemclass",
    "class/src/plugininstance.js~PluginInstanceList.html#instance-member-itemClass",
    "src/plugininstance.js~PluginInstanceList#itemClass",
    "member"
  ],
  [
    "src/plugininstance.js~plugininstancelist#post",
    "class/src/plugininstance.js~PluginInstanceList.html#instance-method-post",
    "src/plugininstance.js~PluginInstanceList#post",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstanceparameter#constructor",
    "class/src/plugininstance.js~PluginInstanceParameter.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstanceParameter#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstanceparameter#getplugininstance",
    "class/src/plugininstance.js~PluginInstanceParameter.html#instance-method-getPluginInstance",
    "src/plugininstance.js~PluginInstanceParameter#getPluginInstance",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstanceparameter#getpluginparameter",
    "class/src/plugininstance.js~PluginInstanceParameter.html#instance-method-getPluginParameter",
    "src/plugininstance.js~PluginInstanceParameter#getPluginParameter",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstanceparameterlist#constructor",
    "class/src/plugininstance.js~PluginInstanceParameterList.html#instance-constructor-constructor",
    "src/plugininstance.js~PluginInstanceParameterList#constructor",
    "method"
  ],
  [
    "src/plugininstance.js~plugininstanceparameterlist#itemclass",
    "class/src/plugininstance.js~PluginInstanceParameterList.html#instance-member-itemClass",
    "src/plugininstance.js~PluginInstanceParameterList#itemClass",
    "member"
  ],
  [
    "src/pluginparameter.js",
    "file/src/pluginparameter.js.html",
    "src/pluginparameter.js",
    "file"
  ],
  [
    "src/pluginparameter.js~pluginparameter#constructor",
    "class/src/pluginparameter.js~PluginParameter.html#instance-constructor-constructor",
    "src/pluginparameter.js~PluginParameter#constructor",
    "method"
  ],
  [
    "src/pluginparameter.js~pluginparameter#getplugin",
    "class/src/pluginparameter.js~PluginParameter.html#instance-method-getPlugin",
    "src/pluginparameter.js~PluginParameter#getPlugin",
    "method"
  ],
  [
    "src/pluginparameter.js~pluginparameterlist#constructor",
    "class/src/pluginparameter.js~PluginParameterList.html#instance-constructor-constructor",
    "src/pluginparameter.js~PluginParameterList#constructor",
    "method"
  ],
  [
    "src/pluginparameter.js~pluginparameterlist#getplugin",
    "class/src/pluginparameter.js~PluginParameterList.html#instance-method-getPlugin",
    "src/pluginparameter.js~PluginParameterList#getPlugin",
    "method"
  ],
  [
    "src/pluginparameter.js~pluginparameterlist#itemclass",
    "class/src/pluginparameter.js~PluginParameterList.html#instance-member-itemClass",
    "src/pluginparameter.js~PluginParameterList#itemClass",
    "member"
  ],
  [
    "src/request.js",
    "file/src/request.js.html",
    "src/request.js",
    "file"
  ],
  [
    "src/request.js~request#_getconfig",
    "class/src/request.js~Request.html#instance-method-_getConfig",
    "src/request.js~Request#_getConfig",
    "method"
  ],
  [
    "src/request.js~request#_postorput",
    "class/src/request.js~Request.html#instance-method-_postOrPut",
    "src/request.js~Request#_postOrPut",
    "method"
  ],
  [
    "src/request.js~request#auth",
    "class/src/request.js~Request.html#instance-member-auth",
    "src/request.js~Request#auth",
    "member"
  ],
  [
    "src/request.js~request#constructor",
    "class/src/request.js~Request.html#instance-constructor-constructor",
    "src/request.js~Request#constructor",
    "method"
  ],
  [
    "src/request.js~request#contenttype",
    "class/src/request.js~Request.html#instance-member-contentType",
    "src/request.js~Request#contentType",
    "member"
  ],
  [
    "src/request.js~request#delete",
    "class/src/request.js~Request.html#instance-method-delete",
    "src/request.js~Request#delete",
    "method"
  ],
  [
    "src/request.js~request#get",
    "class/src/request.js~Request.html#instance-method-get",
    "src/request.js~Request#get",
    "method"
  ],
  [
    "src/request.js~request#post",
    "class/src/request.js~Request.html#instance-method-post",
    "src/request.js~Request#post",
    "method"
  ],
  [
    "src/request.js~request#put",
    "class/src/request.js~Request.html#instance-method-put",
    "src/request.js~Request#put",
    "method"
  ],
  [
    "src/request.js~request#timeout",
    "class/src/request.js~Request.html#instance-member-timeout",
    "src/request.js~Request#timeout",
    "member"
  ],
  [
    "src/request.js~request._callaxios",
    "class/src/request.js~Request.html#static-method-_callAxios",
    "src/request.js~Request._callAxios",
    "method"
  ],
  [
    "src/request.js~request._handlerequesterror",
    "class/src/request.js~Request.html#static-method-_handleRequestError",
    "src/request.js~Request._handleRequestError",
    "method"
  ],
  [
    "src/request.js~request.runasynctask",
    "class/src/request.js~Request.html#static-method-runAsyncTask",
    "src/request.js~Request.runAsyncTask",
    "method"
  ],
  [
    "src/resource.js",
    "file/src/resource.js.html",
    "src/resource.js",
    "file"
  ],
  [
    "src/resource.js~itemresource#_delete",
    "class/src/resource.js~ItemResource.html#instance-method-_delete",
    "src/resource.js~ItemResource#_delete",
    "method"
  ],
  [
    "src/resource.js~itemresource#_getresource",
    "class/src/resource.js~ItemResource.html#instance-method-_getResource",
    "src/resource.js~ItemResource#_getResource",
    "method"
  ],
  [
    "src/resource.js~itemresource#_put",
    "class/src/resource.js~ItemResource.html#instance-method-_put",
    "src/resource.js~ItemResource#_put",
    "method"
  ],
  [
    "src/resource.js~itemresource#collection",
    "class/src/resource.js~ItemResource.html#instance-member-collection",
    "src/resource.js~ItemResource#collection",
    "member"
  ],
  [
    "src/resource.js~itemresource#constructor",
    "class/src/resource.js~ItemResource.html#instance-constructor-constructor",
    "src/resource.js~ItemResource#constructor",
    "method"
  ],
  [
    "src/resource.js~itemresource#data",
    "class/src/resource.js~ItemResource.html#instance-get-data",
    "src/resource.js~ItemResource#data",
    "member"
  ],
  [
    "src/resource.js~itemresource#get",
    "class/src/resource.js~ItemResource.html#instance-method-get",
    "src/resource.js~ItemResource#get",
    "method"
  ],
  [
    "src/resource.js~itemresource#getputdataparameters",
    "class/src/resource.js~ItemResource.html#instance-method-getPUTDataParameters",
    "src/resource.js~ItemResource#getPUTDataParameters",
    "method"
  ],
  [
    "src/resource.js~itemresource#isempty",
    "class/src/resource.js~ItemResource.html#instance-get-isEmpty",
    "src/resource.js~ItemResource#isEmpty",
    "member"
  ],
  [
    "src/resource.js~itemresource#item",
    "class/src/resource.js~ItemResource.html#instance-member-item",
    "src/resource.js~ItemResource#item",
    "member"
  ],
  [
    "src/resource.js~listresource#_getnextorpreviouspage",
    "class/src/resource.js~ListResource.html#instance-method-_getNextOrPreviousPage",
    "src/resource.js~ListResource#_getNextOrPreviousPage",
    "method"
  ],
  [
    "src/resource.js~listresource#_getresource",
    "class/src/resource.js~ListResource.html#instance-method-_getResource",
    "src/resource.js~ListResource#_getResource",
    "method"
  ],
  [
    "src/resource.js~listresource#_post",
    "class/src/resource.js~ListResource.html#instance-method-_post",
    "src/resource.js~ListResource#_post",
    "method"
  ],
  [
    "src/resource.js~listresource#collection",
    "class/src/resource.js~ListResource.html#instance-member-collection",
    "src/resource.js~ListResource#collection",
    "member"
  ],
  [
    "src/resource.js~listresource#constructor",
    "class/src/resource.js~ListResource.html#instance-constructor-constructor",
    "src/resource.js~ListResource#constructor",
    "method"
  ],
  [
    "src/resource.js~listresource#get",
    "class/src/resource.js~ListResource.html#instance-method-get",
    "src/resource.js~ListResource#get",
    "method"
  ],
  [
    "src/resource.js~listresource#getitems",
    "class/src/resource.js~ListResource.html#instance-method-getItems",
    "src/resource.js~ListResource#getItems",
    "method"
  ],
  [
    "src/resource.js~listresource#getnextpage",
    "class/src/resource.js~ListResource.html#instance-method-getNextPage",
    "src/resource.js~ListResource#getNextPage",
    "method"
  ],
  [
    "src/resource.js~listresource#getpostdataparameters",
    "class/src/resource.js~ListResource.html#instance-method-getPOSTDataParameters",
    "src/resource.js~ListResource#getPOSTDataParameters",
    "method"
  ],
  [
    "src/resource.js~listresource#getpreviouspage",
    "class/src/resource.js~ListResource.html#instance-method-getPreviousPage",
    "src/resource.js~ListResource#getPreviousPage",
    "method"
  ],
  [
    "src/resource.js~listresource#getsearch",
    "class/src/resource.js~ListResource.html#instance-method-getSearch",
    "src/resource.js~ListResource#getSearch",
    "method"
  ],
  [
    "src/resource.js~listresource#getsearchparameters",
    "class/src/resource.js~ListResource.html#instance-method-getSearchParameters",
    "src/resource.js~ListResource#getSearchParameters",
    "method"
  ],
  [
    "src/resource.js~listresource#hasnextpage",
    "class/src/resource.js~ListResource.html#instance-get-hasNextPage",
    "src/resource.js~ListResource#hasNextPage",
    "member"
  ],
  [
    "src/resource.js~listresource#haspreviouspage",
    "class/src/resource.js~ListResource.html#instance-get-hasPreviousPage",
    "src/resource.js~ListResource#hasPreviousPage",
    "member"
  ],
  [
    "src/resource.js~listresource#isempty",
    "class/src/resource.js~ListResource.html#instance-get-isEmpty",
    "src/resource.js~ListResource#isEmpty",
    "member"
  ],
  [
    "src/resource.js~listresource#itemclass",
    "class/src/resource.js~ListResource.html#instance-member-itemClass",
    "src/resource.js~ListResource#itemClass",
    "member"
  ],
  [
    "src/resource.js~listresource#queryurl",
    "class/src/resource.js~ListResource.html#instance-member-queryUrl",
    "src/resource.js~ListResource#queryUrl",
    "member"
  ],
  [
    "src/resource.js~listresource#searchparams",
    "class/src/resource.js~ListResource.html#instance-member-searchParams",
    "src/resource.js~ListResource#searchParams",
    "member"
  ],
  [
    "src/resource.js~resource#auth",
    "class/src/resource.js~Resource.html#instance-member-auth",
    "src/resource.js~Resource#auth",
    "member"
  ],
  [
    "src/resource.js~resource#clone",
    "class/src/resource.js~Resource.html#instance-method-clone",
    "src/resource.js~Resource#clone",
    "method"
  ],
  [
    "src/resource.js~resource#collection",
    "class/src/resource.js~Resource.html#instance-member-collection",
    "src/resource.js~Resource#collection",
    "member"
  ],
  [
    "src/resource.js~resource#constructor",
    "class/src/resource.js~Resource.html#instance-constructor-constructor",
    "src/resource.js~Resource#constructor",
    "method"
  ],
  [
    "src/resource.js~resource#contenttype",
    "class/src/resource.js~Resource.html#instance-member-contentType",
    "src/resource.js~Resource#contentType",
    "member"
  ],
  [
    "src/resource.js~resource#url",
    "class/src/resource.js~Resource.html#instance-member-url",
    "src/resource.js~Resource#url",
    "member"
  ],
  [
    "src/tag.js",
    "file/src/tag.js.html",
    "src/tag.js",
    "file"
  ],
  [
    "src/tag.js~feedtaglist#constructor",
    "class/src/tag.js~FeedTagList.html#instance-constructor-constructor",
    "src/tag.js~FeedTagList#constructor",
    "method"
  ],
  [
    "src/tag.js~feedtaglist#getfeed",
    "class/src/tag.js~FeedTagList.html#instance-method-getFeed",
    "src/tag.js~FeedTagList#getFeed",
    "method"
  ],
  [
    "src/tag.js~feedtaglist#itemclass",
    "class/src/tag.js~FeedTagList.html#instance-member-itemClass",
    "src/tag.js~FeedTagList#itemClass",
    "member"
  ],
  [
    "src/tag.js~feedtagginglist#constructor",
    "class/src/tag.js~FeedTaggingList.html#instance-constructor-constructor",
    "src/tag.js~FeedTaggingList#constructor",
    "method"
  ],
  [
    "src/tag.js~feedtagginglist#getfeed",
    "class/src/tag.js~FeedTaggingList.html#instance-method-getFeed",
    "src/tag.js~FeedTaggingList#getFeed",
    "method"
  ],
  [
    "src/tag.js~feedtagginglist#itemclass",
    "class/src/tag.js~FeedTaggingList.html#instance-member-itemClass",
    "src/tag.js~FeedTaggingList#itemClass",
    "member"
  ],
  [
    "src/tag.js~feedtagginglist#post",
    "class/src/tag.js~FeedTaggingList.html#instance-method-post",
    "src/tag.js~FeedTaggingList#post",
    "method"
  ],
  [
    "src/tag.js~tag#constructor",
    "class/src/tag.js~Tag.html#instance-constructor-constructor",
    "src/tag.js~Tag#constructor",
    "method"
  ],
  [
    "src/tag.js~tag#delete",
    "class/src/tag.js~Tag.html#instance-method-delete",
    "src/tag.js~Tag#delete",
    "method"
  ],
  [
    "src/tag.js~tag#gettaggedfeeds",
    "class/src/tag.js~Tag.html#instance-method-getTaggedFeeds",
    "src/tag.js~Tag#getTaggedFeeds",
    "method"
  ],
  [
    "src/tag.js~tag#gettaggings",
    "class/src/tag.js~Tag.html#instance-method-getTaggings",
    "src/tag.js~Tag#getTaggings",
    "method"
  ],
  [
    "src/tag.js~tag#put",
    "class/src/tag.js~Tag.html#instance-method-put",
    "src/tag.js~Tag#put",
    "method"
  ],
  [
    "src/tag.js~tagfeedlist#constructor",
    "class/src/tag.js~TagFeedList.html#instance-constructor-constructor",
    "src/tag.js~TagFeedList#constructor",
    "method"
  ],
  [
    "src/tag.js~tagfeedlist#gettag",
    "class/src/tag.js~TagFeedList.html#instance-method-getTag",
    "src/tag.js~TagFeedList#getTag",
    "method"
  ],
  [
    "src/tag.js~tagfeedlist#itemclass",
    "class/src/tag.js~TagFeedList.html#instance-member-itemClass",
    "src/tag.js~TagFeedList#itemClass",
    "member"
  ],
  [
    "src/tag.js~taglist#constructor",
    "class/src/tag.js~TagList.html#instance-constructor-constructor",
    "src/tag.js~TagList#constructor",
    "method"
  ],
  [
    "src/tag.js~taglist#getfeeds",
    "class/src/tag.js~TagList.html#instance-method-getFeeds",
    "src/tag.js~TagList#getFeeds",
    "method"
  ],
  [
    "src/tag.js~taglist#itemclass",
    "class/src/tag.js~TagList.html#instance-member-itemClass",
    "src/tag.js~TagList#itemClass",
    "member"
  ],
  [
    "src/tag.js~taglist#post",
    "class/src/tag.js~TagList.html#instance-method-post",
    "src/tag.js~TagList#post",
    "method"
  ],
  [
    "src/tag.js~tagtagginglist#constructor",
    "class/src/tag.js~TagTaggingList.html#instance-constructor-constructor",
    "src/tag.js~TagTaggingList#constructor",
    "method"
  ],
  [
    "src/tag.js~tagtagginglist#gettag",
    "class/src/tag.js~TagTaggingList.html#instance-method-getTag",
    "src/tag.js~TagTaggingList#getTag",
    "method"
  ],
  [
    "src/tag.js~tagtagginglist#itemclass",
    "class/src/tag.js~TagTaggingList.html#instance-member-itemClass",
    "src/tag.js~TagTaggingList#itemClass",
    "member"
  ],
  [
    "src/tag.js~tagtagginglist#post",
    "class/src/tag.js~TagTaggingList.html#instance-method-post",
    "src/tag.js~TagTaggingList#post",
    "method"
  ],
  [
    "src/tag.js~tagging#constructor",
    "class/src/tag.js~Tagging.html#instance-constructor-constructor",
    "src/tag.js~Tagging#constructor",
    "method"
  ],
  [
    "src/tag.js~tagging#delete",
    "class/src/tag.js~Tagging.html#instance-method-delete",
    "src/tag.js~Tagging#delete",
    "method"
  ],
  [
    "src/tag.js~tagging#getfeed",
    "class/src/tag.js~Tagging.html#instance-method-getFeed",
    "src/tag.js~Tagging#getFeed",
    "method"
  ],
  [
    "src/tag.js~tagging#gettag",
    "class/src/tag.js~Tagging.html#instance-method-getTag",
    "src/tag.js~Tagging#getTag",
    "method"
  ],
  [
    "src/uploadedfile.js",
    "file/src/uploadedfile.js.html",
    "src/uploadedfile.js",
    "file"
  ],
  [
    "src/uploadedfile.js~uploadedfile#constructor",
    "class/src/uploadedfile.js~UploadedFile.html#instance-constructor-constructor",
    "src/uploadedfile.js~UploadedFile#constructor",
    "method"
  ],
  [
    "src/uploadedfile.js~uploadedfile#delete",
    "class/src/uploadedfile.js~UploadedFile.html#instance-method-delete",
    "src/uploadedfile.js~UploadedFile#delete",
    "method"
  ],
  [
    "src/uploadedfile.js~uploadedfile#getfileblob",
    "class/src/uploadedfile.js~UploadedFile.html#instance-method-getFileBlob",
    "src/uploadedfile.js~UploadedFile#getFileBlob",
    "method"
  ],
  [
    "src/uploadedfile.js~uploadedfile#put",
    "class/src/uploadedfile.js~UploadedFile.html#instance-method-put",
    "src/uploadedfile.js~UploadedFile#put",
    "method"
  ],
  [
    "src/uploadedfile.js~uploadedfilelist#constructor",
    "class/src/uploadedfile.js~UploadedFileList.html#instance-constructor-constructor",
    "src/uploadedfile.js~UploadedFileList#constructor",
    "method"
  ],
  [
    "src/uploadedfile.js~uploadedfilelist#itemclass",
    "class/src/uploadedfile.js~UploadedFileList.html#instance-member-itemClass",
    "src/uploadedfile.js~UploadedFileList#itemClass",
    "member"
  ],
  [
    "src/uploadedfile.js~uploadedfilelist#post",
    "class/src/uploadedfile.js~UploadedFileList.html#instance-method-post",
    "src/uploadedfile.js~UploadedFileList#post",
    "method"
  ],
  [
    "src/user.js",
    "file/src/user.js.html",
    "src/user.js",
    "file"
  ],
  [
    "src/user.js~user#constructor",
    "class/src/user.js~User.html#instance-constructor-constructor",
    "src/user.js~User#constructor",
    "method"
  ],
  [
    "src/user.js~user#put",
    "class/src/user.js~User.html#instance-method-put",
    "src/user.js~User#put",
    "method"
  ]
]