window.esdocSearchIndex = [
  [
    "@fnndsc/chrisstoreapi~collection",
    "class/src/cj.js~Collection.html",
    "<span>Collection</span> <span class=\"search-result-import-path\">@fnndsc/chrisstoreapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisstoreapi~request",
    "class/src/request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">@fnndsc/chrisstoreapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisstoreapi~requestexception",
    "class/src/exception.js~RequestException.html",
    "<span>RequestException</span> <span class=\"search-result-import-path\">@fnndsc/chrisstoreapi</span>",
    "class"
  ],
  [
    "@fnndsc/chrisstoreapi~storeclient",
    "class/src/client.js~StoreClient.html",
    "<span>StoreClient</span> <span class=\"search-result-import-path\">@fnndsc/chrisstoreapi</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/cj.js",
    "file/src/cj.js.html",
    "src/cj.js",
    "file"
  ],
  [
    "src/cj.js~collection.geterrormessage",
    "class/src/cj.js~Collection.html#static-method-getErrorMessage",
    "src/cj.js~Collection.getErrorMessage",
    "method"
  ],
  [
    "src/cj.js~collection.getitemdescriptors",
    "class/src/cj.js~Collection.html#static-method-getItemDescriptors",
    "src/cj.js~Collection.getItemDescriptors",
    "method"
  ],
  [
    "src/cj.js~collection.getlinkrelationurls",
    "class/src/cj.js~Collection.html#static-method-getLinkRelationUrls",
    "src/cj.js~Collection.getLinkRelationUrls",
    "method"
  ],
  [
    "src/cj.js~collection.getqueryparameters",
    "class/src/cj.js~Collection.html#static-method-getQueryParameters",
    "src/cj.js~Collection.getQueryParameters",
    "method"
  ],
  [
    "src/cj.js~collection.gettemplatedescriptornames",
    "class/src/cj.js~Collection.html#static-method-getTemplateDescriptorNames",
    "src/cj.js~Collection.getTemplateDescriptorNames",
    "method"
  ],
  [
    "src/cj.js~collection.geturl",
    "class/src/cj.js~Collection.html#static-method-getUrl",
    "src/cj.js~Collection.getUrl",
    "method"
  ],
  [
    "src/cj.js~collection.maketemplate",
    "class/src/cj.js~Collection.html#static-method-makeTemplate",
    "src/cj.js~Collection.makeTemplate",
    "method"
  ],
  [
    "src/client.js",
    "file/src/client.js.html",
    "src/client.js",
    "file"
  ],
  [
    "src/client.js~storeclient#_fetchcollection",
    "class/src/client.js~StoreClient.html#instance-method-_fetchCollection",
    "src/client.js~StoreClient#_fetchCollection",
    "method"
  ],
  [
    "src/client.js~storeclient#_getitemresourcedata",
    "class/src/client.js~StoreClient.html#instance-method-_getItemResourceData",
    "src/client.js~StoreClient#_getItemResourceData",
    "method"
  ],
  [
    "src/client.js~storeclient#_getlistresourcedata",
    "class/src/client.js~StoreClient.html#instance-method-_getListResourceData",
    "src/client.js~StoreClient#_getListResourceData",
    "method"
  ],
  [
    "src/client.js~storeclient#_getresourcerelatedlistdata",
    "class/src/client.js~StoreClient.html#instance-method-_getResourceRelatedListData",
    "src/client.js~StoreClient#_getResourceRelatedListData",
    "method"
  ],
  [
    "src/client.js~storeclient#_removeitemresource",
    "class/src/client.js~StoreClient.html#instance-method-_removeItemResource",
    "src/client.js~StoreClient#_removeItemResource",
    "method"
  ],
  [
    "src/client.js~storeclient#addplugin",
    "class/src/client.js~StoreClient.html#instance-method-addPlugin",
    "src/client.js~StoreClient#addPlugin",
    "method"
  ],
  [
    "src/client.js~storeclient#auth",
    "class/src/client.js~StoreClient.html#instance-member-auth",
    "src/client.js~StoreClient#auth",
    "member"
  ],
  [
    "src/client.js~storeclient#constructor",
    "class/src/client.js~StoreClient.html#instance-constructor-constructor",
    "src/client.js~StoreClient#constructor",
    "method"
  ],
  [
    "src/client.js~storeclient#contenttype",
    "class/src/client.js~StoreClient.html#instance-member-contentType",
    "src/client.js~StoreClient#contentType",
    "member"
  ],
  [
    "src/client.js~storeclient#getpipeline",
    "class/src/client.js~StoreClient.html#instance-method-getPipeline",
    "src/client.js~StoreClient#getPipeline",
    "method"
  ],
  [
    "src/client.js~storeclient#getpipelinedefaultparameters",
    "class/src/client.js~StoreClient.html#instance-method-getPipelineDefaultParameters",
    "src/client.js~StoreClient#getPipelineDefaultParameters",
    "method"
  ],
  [
    "src/client.js~storeclient#getpipelinepipings",
    "class/src/client.js~StoreClient.html#instance-method-getPipelinePipings",
    "src/client.js~StoreClient#getPipelinePipings",
    "method"
  ],
  [
    "src/client.js~storeclient#getpipelineplugins",
    "class/src/client.js~StoreClient.html#instance-method-getPipelinePlugins",
    "src/client.js~StoreClient#getPipelinePlugins",
    "method"
  ],
  [
    "src/client.js~storeclient#getpipelines",
    "class/src/client.js~StoreClient.html#instance-method-getPipelines",
    "src/client.js~StoreClient#getPipelines",
    "method"
  ],
  [
    "src/client.js~storeclient#getplugin",
    "class/src/client.js~StoreClient.html#instance-method-getPlugin",
    "src/client.js~StoreClient#getPlugin",
    "method"
  ],
  [
    "src/client.js~storeclient#getpluginparameters",
    "class/src/client.js~StoreClient.html#instance-method-getPluginParameters",
    "src/client.js~StoreClient#getPluginParameters",
    "method"
  ],
  [
    "src/client.js~storeclient#getplugins",
    "class/src/client.js~StoreClient.html#instance-method-getPlugins",
    "src/client.js~StoreClient#getPlugins",
    "method"
  ],
  [
    "src/client.js~storeclient#getuser",
    "class/src/client.js~StoreClient.html#instance-method-getUser",
    "src/client.js~StoreClient#getUser",
    "method"
  ],
  [
    "src/client.js~storeclient#modifypipeline",
    "class/src/client.js~StoreClient.html#instance-method-modifyPipeline",
    "src/client.js~StoreClient#modifyPipeline",
    "method"
  ],
  [
    "src/client.js~storeclient#modifyplugin",
    "class/src/client.js~StoreClient.html#instance-method-modifyPlugin",
    "src/client.js~StoreClient#modifyPlugin",
    "method"
  ],
  [
    "src/client.js~storeclient#pipelinesqueryurl",
    "class/src/client.js~StoreClient.html#instance-member-pipelinesQueryUrl",
    "src/client.js~StoreClient#pipelinesQueryUrl",
    "member"
  ],
  [
    "src/client.js~storeclient#pipelinesurl",
    "class/src/client.js~StoreClient.html#instance-member-pipelinesUrl",
    "src/client.js~StoreClient#pipelinesUrl",
    "member"
  ],
  [
    "src/client.js~storeclient#removepipeline",
    "class/src/client.js~StoreClient.html#instance-method-removePipeline",
    "src/client.js~StoreClient#removePipeline",
    "method"
  ],
  [
    "src/client.js~storeclient#removeplugin",
    "class/src/client.js~StoreClient.html#instance-method-removePlugin",
    "src/client.js~StoreClient#removePlugin",
    "method"
  ],
  [
    "src/client.js~storeclient#setpipelinesurls",
    "class/src/client.js~StoreClient.html#instance-method-setPipelinesUrls",
    "src/client.js~StoreClient#setPipelinesUrls",
    "method"
  ],
  [
    "src/client.js~storeclient#storequeryurl",
    "class/src/client.js~StoreClient.html#instance-member-storeQueryUrl",
    "src/client.js~StoreClient#storeQueryUrl",
    "member"
  ],
  [
    "src/client.js~storeclient#storeurl",
    "class/src/client.js~StoreClient.html#instance-member-storeUrl",
    "src/client.js~StoreClient#storeUrl",
    "member"
  ],
  [
    "src/client.js~storeclient#timeout",
    "class/src/client.js~StoreClient.html#instance-member-timeout",
    "src/client.js~StoreClient#timeout",
    "member"
  ],
  [
    "src/client.js~storeclient#updateuser",
    "class/src/client.js~StoreClient.html#instance-method-updateUser",
    "src/client.js~StoreClient#updateUser",
    "method"
  ],
  [
    "src/client.js~storeclient.createuser",
    "class/src/client.js~StoreClient.html#static-method-createUser",
    "src/client.js~StoreClient.createUser",
    "method"
  ],
  [
    "src/client.js~storeclient.getauthtoken",
    "class/src/client.js~StoreClient.html#static-method-getAuthToken",
    "src/client.js~StoreClient.getAuthToken",
    "method"
  ],
  [
    "src/client.js~storeclient.getdatafromcollection",
    "class/src/client.js~StoreClient.html#static-method-getDataFromCollection",
    "src/client.js~StoreClient.getDataFromCollection",
    "method"
  ],
  [
    "src/client.js~storeclient.runasynctask",
    "class/src/client.js~StoreClient.html#static-method-runAsyncTask",
    "src/client.js~StoreClient.runAsyncTask",
    "method"
  ],
  [
    "src/exception.js",
    "file/src/exception.js.html",
    "src/exception.js",
    "file"
  ],
  [
    "src/exception.js~requestexception#constructor",
    "class/src/exception.js~RequestException.html#instance-constructor-constructor",
    "src/exception.js~RequestException#constructor",
    "method"
  ],
  [
    "src/exception.js~requestexception#name",
    "class/src/exception.js~RequestException.html#instance-member-name",
    "src/exception.js~RequestException#name",
    "member"
  ],
  [
    "src/exception.js~requestexception#request",
    "class/src/exception.js~RequestException.html#instance-member-request",
    "src/exception.js~RequestException#request",
    "member"
  ],
  [
    "src/exception.js~requestexception#response",
    "class/src/exception.js~RequestException.html#instance-member-response",
    "src/exception.js~RequestException#response",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/request.js",
    "file/src/request.js.html",
    "src/request.js",
    "file"
  ],
  [
    "src/request.js~request#_getconfig",
    "class/src/request.js~Request.html#instance-method-_getConfig",
    "src/request.js~Request#_getConfig",
    "method"
  ],
  [
    "src/request.js~request#_postorput",
    "class/src/request.js~Request.html#instance-method-_postOrPut",
    "src/request.js~Request#_postOrPut",
    "method"
  ],
  [
    "src/request.js~request#auth",
    "class/src/request.js~Request.html#instance-member-auth",
    "src/request.js~Request#auth",
    "member"
  ],
  [
    "src/request.js~request#constructor",
    "class/src/request.js~Request.html#instance-constructor-constructor",
    "src/request.js~Request#constructor",
    "method"
  ],
  [
    "src/request.js~request#contenttype",
    "class/src/request.js~Request.html#instance-member-contentType",
    "src/request.js~Request#contentType",
    "member"
  ],
  [
    "src/request.js~request#delete",
    "class/src/request.js~Request.html#instance-method-delete",
    "src/request.js~Request#delete",
    "method"
  ],
  [
    "src/request.js~request#get",
    "class/src/request.js~Request.html#instance-method-get",
    "src/request.js~Request#get",
    "method"
  ],
  [
    "src/request.js~request#post",
    "class/src/request.js~Request.html#instance-method-post",
    "src/request.js~Request#post",
    "method"
  ],
  [
    "src/request.js~request#put",
    "class/src/request.js~Request.html#instance-method-put",
    "src/request.js~Request#put",
    "method"
  ],
  [
    "src/request.js~request#timeout",
    "class/src/request.js~Request.html#instance-member-timeout",
    "src/request.js~Request#timeout",
    "member"
  ],
  [
    "src/request.js~request._callaxios",
    "class/src/request.js~Request.html#static-method-_callAxios",
    "src/request.js~Request._callAxios",
    "method"
  ],
  [
    "src/request.js~request._handlerequesterror",
    "class/src/request.js~Request.html#static-method-_handleRequestError",
    "src/request.js~Request._handleRequestError",
    "method"
  ],
  [
    "src/request.js~request.runasynctask",
    "class/src/request.js~Request.html#static-method-runAsyncTask",
    "src/request.js~Request.runAsyncTask",
    "method"
  ]
]